ID_IDIOMA^CLAVE^VALOR
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^0.MOD1_300^Systemfehler Nummer 300 in System 0 Modul 1
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^1.ETIQUETA_001^Der Schlüsselwert kann nicht wiederholt werden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^1.MAIL_001^Die Mail-Server-Authentifizierung ist fehlgeschlagen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^1.MAIL_002^Ohne Verbindung zum Mail-Server, speichern der E-Mail für einen späteren Zeitpunkt
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^1.MAIL_003^Ein Fehler ist während des Versendens aufgetreten, bitte verifizieren Sie den Log.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^1.MAIL_004^Ein Fehler ist beim Speichern in der Datenbank aufgetreten
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^1.MAIL_005^Anhangsdatei nicht gefunden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^1.MOD1_300^Systemfehler Nummer 300 in System 1 Modul 1
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^1.PERFIL_001^Doppelte Namen sind nicht zulässig
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^1.PERMISO_001^Doppelte Namen sind nicht zulässig
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^1.PERMISO_002^Es war nicht möglich Befugnisse zu erteilen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^1.VALIDA_00^Die Felder: {0}, müssen ausgefüllt werden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.CAT_01^Die Bewerbung [1] ist bereits registriert
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.CAT_02^Der Katalog [1] ist bereits für die Bewerbung [2] registriert
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.EXC_001^Ein Fehler ist während der SQL Ausführung aufgetreten
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.EXC_002^Datenbank Verbindungsproblem
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.EXC_003^Es gibt einen Satzfehler
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.EXC_004^Es gibt einen Satzfehler in den Daten
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.EXC_005^Die Anweisung generiert einen Fehler der Integrität
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.EXC_006^Es ist nicht möglich das Datenbankschloss zu erhalten.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.GEN_000^Ein Systemfehler ist aufgetreten
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.MAIL_001^Die Mail-Server-Authentifizierung ist fehlgeschlagen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.MAIL_002^Ohne Verbindung zum Mail-Server, speichern der E-Mail für einen späteren Zeitpunkt
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.MAIL_003^Ein Fehler ist während des Versendens aufgetreten, bitte verifizieren Sie den Log.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.MAIL_004^Ein Fehler ist beim Speichern in der Datenbank aufgetreten
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.MAIL_005^Anhangsdatei nicht gefunden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^2.MOD1_100^Ein Fehler ist beim Ausführen der Datei [NomArchivo] aufgetreten
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^CORREO.TITULO^Test E-Mails senden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^ERROR_NO_CATALOGADO^Nicht im System klassifiziert.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^ETIQUETA.DATA.CLAVE^Schlüssel
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^ETIQUETA.DATA.CLAVE.REQUIRED^Das Kettenfeld mus ausgefüllt werden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^ETIQUETA.DATA.VALOR^Standardsprache
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^ETIQUETA.DATA.VALOR.REQUIRED^Das Wertefeld muss ausgefüllt werden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^ETIQUETA.NEW.HEADER^Neue Kette
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ACCESS.ERRORMSG^Sie haben keine Erlaubnis auf diese Seite zu zugreifen 
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ACCESS.HEADER^Fehler beim Zugriff
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ACEPTAR^Akzeptieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ACTIVA^Aktivieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ADD^Hinzufügen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.AMBIENTE.DESARROLLO^DEV
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.AMBIENTE.INTEGRACION^INTEGRA
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.AMBIENTE.QA^QAS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.AUTORIZA^Authorisieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.AYUDA^Hilfe
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.AYUDA.GRAL^Generelle Hilfe
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.AYUDA.MANUALUSR^Benutzerhandbuch
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.BUSCAR^Finden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.CADENAS^System Zeichenfolge
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.CADENAS.CLAVE^Schlüssel
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.CADENAS.IDIOMA^Sprache
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.CADENAS.MESSAGES^Protokollierte Nachrichten
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.CADENAS.STRINGS^Protokollierte Zeichenfolge
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.CADENAS.VALOR^Wert
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.CADENAS.VALORESPARA^Werte für
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.CANCELAR^Abbrechen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.CHOOSELANG^Wählen Sie Ihre Sprache
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.CONFIRMA.HEADER^Bitte bestätigen Sie.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.CONFIRMA.MSGCONFIRMA^Sind Sie sicher, dass Sie die angegebene Aktion ausführen möchten?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.DATA.ACTIVO^Aktiv
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.DATA.ESTATUS^Status
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.DATA.FALSE^Nein
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.DATA.INACTIVO^Inaktiv
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.DATA.TRUE^Ja
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.DETALLE^Details
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.EDITAR^Bearbeiten
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ELIMINAR^Löschen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.EMPTYMESSAGE^Keine Datensätze mit dem angegebenen Filter gefunden.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ERROR.HANDLER.CLASS^Ausnahmeklasse
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ERROR.HANDLER.CODE^Fehlercode
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ERROR.HANDLER.DESC^Fehlerbeschreibung
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ERROR.HANDLER.STACK^Anfrage StackTrace
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ERROR.HANDLER.TITLE^Fehlerbehandlung - Fehler erkannt
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ERROR.HANDLER.TYPE^Ausnahmeart
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ERROR.HANDLER.URI^Angeforderte URL
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.EXCEL^XLS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.EXIT^Verlassen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.EXPLORER.ERRORMSG^Diese Applikation benötigt Mozilla Firefox. Fortfahren ist nicht möglich.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.EXPORT.ALL^Alles exportieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.EXPORT.PAGE^Seite exportieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.EXPORT.PRINT^Drucken
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.EXPORTAR^Exportieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.FILELOADER.ERROR^Fehler in Zeile: %s | Attribut: %s | Anfangsposition: %s | Endposition: %s | Fehler: %s
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.FILTER.WAIT.MESSAGE^Bitte warten Sie, Ihre Anfrage wird ausgeführt
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.GUARDAR^Speichern
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ID^ID
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.IMAGE.SAVE^Rechtsklick mit der Maus und "Bild speichern" auswählen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.IMAGEN^Bild
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.IMPRIMIR^Drucken
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.INACTIVA^Deaktivieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.LIBERAR^Befreien
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.MENSAJES.TITULO^Nachrichten
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.MESSAGES^Systemreihe
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.MOSTRAR^Aufzeigen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.MOSTRAR.IRPAGINA^Gehe zu Seite:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.MOSTRAR.PAGINA^Seite
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.MOSTRAR.PAGINA.ROWS^1,2,3,4,5,10,15,20,25,50,75,100
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.MOSTRAR.PAGINA.X.DE.Y^von
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.MOSTRAR_REGS_PREFIJO^Aufzeigen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.MOSTRAR_REGS_SUFIJO^Aufzeichnungen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.MOUSE.RIGHTBUTTON.MSG^Sie können die rechte Maustaste nicht benutzen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.NOMBREMES^Januar, Februar, März, April, Mai, Juni, Juli, August, September, Oktober, November, Dezember
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.NOMBREMESABREV^JAN, FEB, MÄR, APR, MAI, JUN, JUL, AUG, SEP, OKT, NOV, DEZ
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.NUEVO^Neu
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.OPTS.ALL^Alle
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.PAGINATOR.CURRROWTEMPLATE^Seite: ({currentPage} von {totalPages})
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.PAGINATOR.TEMPLATE^{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {CurrentPageReport} Show {RowsPerPageDropdown} records.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.PAGINATOR.TEMPLATE.NONUMROWS^{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {CurrentPageReport}
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.PDF^PDF
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.REPORTE.AUTOR^Software Werk
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.REPORTE.SISTEMA^ADAN System
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.RESIZE^Anpassen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.RESIZE.MESSAGE^Führen Sie Ihre Anfrage aus um die Ansicht zu aktualisieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.SAVE.EXITO^Information erfolgreich gespeichert
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.SEARCH.ALLFIELDS^Suchen in Alle
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.SEARCH.ALLFIELDS.KEY^Einen Wert registrieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.SELECCIONAR^Wählen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.SESSION.MESSAGE.CONTINUE^Möchten Sie Ihre Sitzung verlängern?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.SESSION.MESSAGE.POST^Sie wurden aus dem System geworfen.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.SESSION.MESSAGE.PRE^Sie werden in wenigen Sekunden aus dem System geworfen.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.SESSION.TITLE^Ihre Sitzung endet in Kürze.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.SWF^Software Werk
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.TITULO^ADAN System
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.AVANCE^Fortschritt im Prozess
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.CANCEL^Abbrechen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.CHOOSE^Auswählen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.FASE^Phase
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.FASE.X.DE.Y^von
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.FILES^1
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.HEADER^Datei Hochladen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.LIMITMESSAGE^Sie können nur eine Datei zur Zeit hochladen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.LIMITSIZE^102400
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.SIZEMESSAGE^Sie können nur Dateien, die kleiner als 100kb sind, hochladen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.STATUS.TITLE^Fortschritt im Prozess
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.TYPEMESSAGE^Sie können Dateien vom Typ gif, jpg, png, txt, csv, xls, zip, rar hochladen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.TYPES^gif|jpe?g|png|txt|csv|xls|zip|rar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.UPLOAD.UPLOAD^Hochladen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.VERSION.LABEL^Version
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.VERSION.NUM^1.0.0
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.VISTAPRELIMINAR^Vorschau
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.ZOOM^Grösse anpassen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.ACTIVA.HEADER^Bitte bestätigen Sie
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.ACTIVA.MSGCONFIRMA^Sind Sie sicher, dass Sie die Sprache aktivieren möchten?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DATA.CODIDIOMA^Sprachcode
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DATA.CODIDIOMA.REQUIRED^Der Sprachencode muss eingetragen werden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DATA.CODIDIOMA.VALIDFORMAT^Der Sprachencode darf ausschliesslich aus kleinen Buchstaben bestehen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DATA.CODPAIS^Ländercode
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DATA.CODPAIS.REQUIRED^Der Ländercode muss eingetragen werden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DATA.CODPAIS.VALIDFORMAT^Der Ländercode darf maximal zwei Grossbuchstaben haben
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DATA.HEADER^Sprachen Einstellung
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DATA.IDIOMA^Sprache
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DATA.IDIOMA.REQUIRED^Das Attribut Sprache muss eingetragen werden, bitte füllen Sie einen Wert ein
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DATA.IDIOMA.VALIDFORMAT^Das Attribut Sprache hat ein falsches Format
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DATA.PREDETERMINADO^Standardsprache
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DESACTIVA.HEADER^Bitte bestätigen Sie
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.DESACTIVA.MSGCONFIRMA^Sind Sie sicher, dass Sie die Sprache deaktivieren möchten?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.REPORTE.NOMBRE^Sprachen Einstellung
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.TITULO^Sprachen Einstellung
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^IDIOMA.UPDATE.HEADER^Sprache aktualisieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Administracion^Administration
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Catalogo^Einfache Kataloge
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.ConfiguracionAMS^Konfigurationen für AMS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Estadistica^Statistiken
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Idioma^Sprachen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Inicio^Start
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Menu^Optionsmenü
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Parametro^Parameter
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Perfil^Profile
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Permiso^Erlaubnis
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Principal^Häufig
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Proceso^Prozesse
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Reporte^Berichte
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Salir^Schliessen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Seguridad^Sicherheit
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^MENU.Template^E-mail Vorlagen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.ACTIVA.HEADER^Profil aktivieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.ACTIVA.MSGCONFIRMA^Sind Sie sicher, dass Sie dieses Profil aktivieren möchten?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.ADD.PERMISO^Erlaubnis hinzufügen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.DATA.HEADER^Registrierte Profile
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.DATA.PERFIL^Profil
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.DATA.PERFIL.REQUIRED^Das Profilfeld muss ausgefüllt werden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.DATA.PERFIL.VALIDFORMAT^Das Profil hat das falsche Format
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.DESACTIVA.HEADER^Profil deaktivieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.DESACTIVA.MSGCONFIRMA^Sind Sie sicher, dass Sie dieses Profil deaktivieren möchten?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.REPORTE.NOMBRE^Profilbericht
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.TITULO^Administrations Profile
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERFIL.UPDATE.HEADER^Profil hinzufügen oder editieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.ACTIVA.HEADER^Erlaubnis aktivieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.ACTIVA.MENU.HEADER^Im Konfigurationsmenü zeigen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.ACTIVA.MENU.MSGCONFIRMA^Sind Sie sicher, dass Sie diese Erlaubnis im Konfigurationsmenü zeigen möchten?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.ACTIVA.MSGCONFIRMA^Sind Sie sicher, dass Sie diese Erlaubnis aktivieren möchten?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.ASIGNAR.HEADER^Erlaubnis zuteilen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.DATA.HEADER^Registrierte Erlaubnisse
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.DATA.MOSTRARENMENU^Im Menü zeigen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.DATA.PERMISO^Erlaubnis
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.DATA.PERMISO.REQUIRED^Das Profilfeld muss ausgefüllt werden
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.DATA.PERMISO.VALIDFORMAT^Das Profil hat das falsche Format
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.DATA.QUITARENMENU^Im Menü verstecken
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.DESACTIVA.HEADER^Erlaubnis deaktivieren
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.DESACTIVA.MENU.HEADER^Im Konfigurationsmenü verstecken
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.DESACTIVA.MENU.MSGCONFIRMA^Sind Sie sicher, dass Sie diese Erlaubnis im Konfigurationsmenü verstecken möchten?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.DESACTIVA.MSGCONFIRMA^Sind Sie sicher, dass Sie diese Erlaubnis deaktivieren möchten?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.FILTRO.HEADER^Filtern mithilfe von Berechtigungen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.FILTRO.PERFIL^Profil
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.REPORTE.NOMBRE^Erlaubnisbericht
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.TITULO^Erlaubnis Manager
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^PERMISO.UPDATE.HEADER^Erlaubnis hinzufügen oder bearbeiten
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^WIZARD.SIMPLE_CATALOG.BEANPACKAGE^Bean Paket
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^WIZARD.SIMPLE_CATALOG.ENTITYNAME^Name der Entität
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^WIZARD.SIMPLE_CATALOG.ENTITYPACKAGE^Weg der Entität
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^WIZARD.SIMPLE_CATALOG.SERVICENAME^Name Service
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^WIZARD.SIMPLE_CATALOG.SERVICEPACKAGE^Serviceweg
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='de' AND COD_PAIS='DE')^GENERAL.SELECCIONE^Wählen...
