IDPERFIL^IDPERMISO
#--Creación de SegPermisoPerfil - Acceso al sistema
(select id from SEG_PERFIL where PERFIL = 'BANNER')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_MAIN')

#--Creación de SegPermisoPerfil - Perfil ADM_AMS
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_MAIN')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_DEV_OPTIONS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'MANUAL_USR_3_AMS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_ADMINISTRACION')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_MENUCONFIG')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_MENUCONFIG_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_MENUCONFIG_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_MENUCONFIG_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_IDIOMA')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_IDIOMA_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_IDIOMA_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_IDIOMA_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_TEMPLATECORREO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_TEMPLATECORREO_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_TEMPLATECORREO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_TEMPLATECORREO_UPDATE')


#--Asignación de SegPermisoPerfil para Administrador de Catálogos
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_UPDATE')
#--Permisos de administrador de catálogos aplicación BASE_APP
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP')
#--Iconlist
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_ICONLIST')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_ICONLIST_TODOS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_ICONLIST_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_ICONLIST_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_ICONLIST_UPDATE')
#--ThemeList
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_THEMESLIST')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_THEMESLIST_TODOS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_THEMESLIST_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_THEMESLIST_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_THEMESLIST_UPDATE')
#--PropiedadesSWF
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TODOS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TODOS_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TODOS_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TODOS_UPDATE')
#--Acceso
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_ACCESO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_ACCESO_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_ACCESO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_ACCESO_UPDATE')
#--Mail
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_MAIL')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_MAIL_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_MAIL_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_MAIL_UPDATE')
#--Mensajes
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_MSG')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_MSG_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_MSG_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_MSG_UPDATE')
#--Logger
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_LOG')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_LOG_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_LOG_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_LOG_UPDATE')
#--Rutas
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_RUTAS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_RUTAS_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_RUTAS_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_RUTAS_UPDATE')
#--Timer Controller
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TIMER')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TIMER_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TIMER_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TIMER_UPDATE')
#--Timer Envio Pendiente
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TIMER_ENVIOPENDIENTE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TIMER_ENVIOPENDIENTE_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TIMER_ENVIOPENDIENTE_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BASE_APP_PROPIEDADESSWF_TIMER_ENVIOPENDIENTE_UPDATE')


#--Permisos de administrador de catálogos aplicación SWF
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF')
#--PropiedadesSWF
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_TODOS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_TODOS_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_TODOS_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_TODOS_UPDATE')
#--Mail
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_MAIL')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_MAIL_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_MAIL_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_MAIL_UPDATE')
#--Mensajes
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_MSG')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_MSG_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_MSG_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_MSG_UPDATE')
#--Logger
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_LOG')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_LOG_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_LOG_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_SWF_PROPIEDADESSWF_LOG_UPDATE')


#--Permisos de administrador de catálogos aplicación BANNER
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_TODOS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_TODOS_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_TODOS_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_TODOS_UPDATE')
#--PropiedadesSWF
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_TODOS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_TODOS_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_TODOS_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_TODOS_UPDATE')
#--Mail
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_MAIL')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_MAIL_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_MAIL_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_MAIL_UPDATE')
#--Mensajes
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_MSG')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_MSG_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_MSG_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_MSG_UPDATE')
#--Logger
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_LOG')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_LOG_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_LOG_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_LOG_UPDATE')
#--Rutas
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_RUTAS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_RUTAS_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_RUTAS_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_PARAMETRO_BANNER_PROPIEDADESSWF_RUTAS_UPDATE')

#--SegPermisoPergil para catalogos nuevos
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_CONFIGURACION')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_CONFIGURACION_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_CONFIGURACION_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_CONFIGURACION_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_APROBACIONES')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_APROBACIONES_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_APROBACIONES_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_APROBACIONES_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_APROBACIONES')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_APROBACIONES_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_APROBACIONES_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_APROBACIONES_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ADMINISTRACION')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ADMINISTRACION_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ADMINISTRACION_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ADMINISTRACION_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ENVIARNOTIFICACIONESPORPERFIL')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ENVIARNOTIFICACIONESPORPERFIL_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ENVIARNOTIFICACIONESPORPERFIL_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ENVIARNOTIFICACIONESPORPERFIL_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ENVIARNOTIFICACIONESUSUARIOSSISTEMA')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ENVIARNOTIFICACIONESUSUARIOSSISTEMA_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ENVIARNOTIFICACIONESUSUARIOSSISTEMA_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_ENVIARNOTIFICACIONESUSUARIOSSISTEMA_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_APROBACIONES')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_APROBACIONES_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_APROBACIONES_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_APROBACIONES_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_REPORTES_CATALOGOREPORTESJASPER')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_REPORTES_CATALOGOREPORTESJASPER_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_REPORTES_CATALOGOREPORTESJASPER_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_REPORTES_CATALOGOREPORTESJASPER_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_SEGUIMIENTOPERFILUSUARIO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_SEGUIMIENTOPERFILUSUARIO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_SEGUIMIENTOPERFILUSUARIO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_SEGUIMIENTOPERFILUSUARIO_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_DELEGACIONPERMISOS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_DELEGACIONPERMISOS_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_DELEGACIONPERMISOS_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_DELEGACIONPERMISOS_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_AUDITORIAREPORTES')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_AUDITORIAREPORTES_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_AUDITORIAREPORTES_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_AUDITORIAREPORTES_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_TRAZABILIDAD')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_TRAZABILIDAD_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_TRAZABILIDAD_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_TRAZABILIDAD_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_AUDITORIASERVICIOSWEB')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_AUDITORIASERVICIOSWEB_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_AUDITORIASERVICIOSWEB_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_AUDITORIASERVICIOSWEB_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOPANTALLAS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOPANTALLAS_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOPANTALLAS_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOPANTALLAS_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOREPORTES')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOREPORTES_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOREPORTES_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOREPORTES_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOTIPOEXPORTACION')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOTIPOEXPORTACION_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOTIPOEXPORTACION_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CATALOGOTIPOEXPORTACION_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_ASIGNAREPORTEPANTALLA')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_ASIGNAREPORTEPANTALLA_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_ASIGNAREPORTEPANTALLA_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_ASIGNAREPORTEPANTALLA_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CALENDARIO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CALENDARIO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CALENDARIO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE_CALENDARIO_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_AUDITORIA_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJO_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJODET')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJODET_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJODET_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJODET_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONREGISTRO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONREGISTRO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONREGISTRO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONREGISTRO_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONREGISTRODETALLE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONREGISTRODETALLE_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONREGISTRODETALLE_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONREGISTRODETALLE_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_NOTIFICA_CATALOGOMETODOCOMUNICACION')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_NOTIFICA_CATALOGOMETODOCOMUNICACION_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_NOTIFICA_CATALOGOMETODOCOMUNICACION_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_NOTIFICA_CATALOGOMETODOCOMUNICACION_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONDETALLEEVIDENCIA')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONDETALLEEVIDENCIA_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONDETALLEEVIDENCIA_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONDETALLEEVIDENCIA_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONFIGURA_REPORTE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOPROCESO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOPROCESO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOPROCESO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOPROCESO_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOESTADOSPROCESO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOESTADOSPROCESO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOESTADOSPROCESO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOESTADOSPROCESO_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOMOTIVOSRECHAZO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOMOTIVOSRECHAZO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOMOTIVOSRECHAZO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOMOTIVOSRECHAZO_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_APROBACION_APROBACIONCONFIGURAFLUJO_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_SEGVACATIONMODE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_SEGVACATIONMODE_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_SEGVACATIONMODE_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_SEGVACATIONMODE_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_BANDEJA')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_BANDEJA_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_BANDEJA_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_NOTIFICACIONES_BANDEJA_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_REPORTES_CATALOGOREPORTESJASPER')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_REPORTES_CATALOGOREPORTESJASPER_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_REPORTES_CATALOGOREPORTESJASPER_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_REPORTES_CATALOGOREPORTESJASPER_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_GESTIONUSUARIOS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_GESTIONUSUARIOS_ASIGNAR')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_GESTIONUSUARIOS_DELETE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_GESTIONUSUARIOS_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_SEGURIDAD_GESTIONUSUARIOS_UPDATE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOORIGENSOLICITUD')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOORIGENSOLICITUD_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOORIGENSOLICITUD_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOORIGENSOLICITUD_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOASOCIARTIPODOCUMAPROCESO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOASOCIARTIPODOCUMAPROCESO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOASOCIARTIPODOCUMAPROCESO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOASOCIARTIPODOCUMAPROCESO_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_ARCHIVO_CATALOGOARCHIVO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_ARCHIVO_CATALOGOARCHIVO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_ARCHIVO_CATALOGOARCHIVO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_ARCHIVO_CATALOGOARCHIVO_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOORDENPROCESO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOORDENPROCESO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOORDENPROCESO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CATALOGOS_PROCESO_CATALOGOORDENPROCESO_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_APROBACIONES_APROBACIONREASIGNARTAREAS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_FUNCIONALIDADES_APROBACIONES_APROBACIONREASIGNARTAREAS_UPDATE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_ADMINISTRACION_GESTIONTIMERS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_ADMINISTRACION_GESTIONTIMERS_EXECUTE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONSULTAS_CONSULTASDINAMICAS')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONSULTAS_CONSULTASDINAMICAS_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONSULTAS_CONSULTASDINAMICAS_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONSULTAS_CONSULTASDINAMICAS_DELETE')

(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONSULTAS_CONSULTASDINAMICASCATALOGO')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONSULTAS_CONSULTASDINAMICASCATALOGO_INSERT')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONSULTAS_CONSULTASDINAMICASCATALOGO_UPDATE')
(select id from SEG_PERFIL where PERFIL = 'BANNER_ADM_AMS')^(select ID from SEG_PERMISO WHERE permiso = 'BASEAPP_CONSULTAS_CONSULTASDINAMICASCATALOGO_DELETE')
