/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */
ALTER TABLE "SEG_PERFIL" ADD CONSTRAINT "PK_SEG_PERFIL" PRIMARY KEY ("ID") USING INDEX;
ALTER TABLE "SEG_PERFIL" ADD CONSTRAINT "UQ_SEG_PERFIL_Perfil" UNIQUE ("PERFIL") USING INDEX;
ALTER TABLE "SEG_PERFIL" ADD CONSTRAINT "CK_ESTATUS_PERFIL" CHECK ("ESTATUS" BETWEEN 0 AND 1);

ALTER TABLE "SEG_PERFIL_USR" ADD CONSTRAINT "PK_SEG_PERFIL_USR" PRIMARY KEY ("IDUSUARIO","IDPERFIL") USING INDEX;

ALTER TABLE "SEG_PERMISO" ADD CONSTRAINT "PK_SEG_PERMISO" PRIMARY KEY ("ID") USING INDEX;
ALTER TABLE "SEG_PERMISO" ADD CONSTRAINT "UQ_SEG_PERMISO_PERMISO" UNIQUE ("PERMISO") USING INDEX;
ALTER TABLE "SEG_PERMISO" ADD CONSTRAINT "CK_ESTATUS_PERMISO" CHECK ("ESTATUS" BETWEEN 0 AND 1);
ALTER TABLE "SEG_PERMISO" ADD CONSTRAINT "CK_MOSTRARMENU_PERMISO" CHECK ("MOSTRARENMENU" BETWEEN 0 AND 1);

ALTER TABLE "SEG_PERMISO_PERFIL" ADD CONSTRAINT "PK_SEG_PERMISO_PERFIL" PRIMARY KEY ("IDPERFIL","IDPERMISO") USING INDEX;

ALTER TABLE "SEG_USUARIO" ADD CONSTRAINT "PK_SEG_USUARIO" PRIMARY KEY ("ID") USING INDEX;
ALTER TABLE "SEG_USUARIO" ADD CONSTRAINT "UQ_SEG_USUARIO_User_Id" UNIQUE ("USER_ID") USING INDEX;
ALTER TABLE "SEG_USUARIO" ADD CONSTRAINT "CK_ESTATUS_USR" CHECK ("ESTATUS" BETWEEN 0 AND 1);

ALTER TABLE "FWK_ACCESO_USR" ADD CONSTRAINT "PK_FWK_ACCESO_USR" PRIMARY KEY ("ID_ACCESO") USING INDEX;

ALTER TABLE "FWK_ACTION_ITEM" ADD CONSTRAINT "CK_FWK_ACTION_ITEM_ENABLED" CHECK (ENABLED BETWEEN 0 AND 1);
ALTER TABLE "FWK_ACTION_ITEM" ADD CONSTRAINT "PK_FWK_ACTION_ITEM" PRIMARY KEY ("ID") USING INDEX;

CREATE INDEX "IXFK_CAT_ADMIN_CAT_APPS" ON "FWK_CAT_ADMIN" ("ID_APP") ;
ALTER TABLE "FWK_CAT_ADMIN" ADD CONSTRAINT "PK_CUPS_FWK_CAT_ADMIN" PRIMARY KEY ("ID_ADMIN") USING INDEX;
ALTER TABLE "FWK_CAT_ADMIN" ADD CONSTRAINT "UQ_APP_ADMIN" UNIQUE ("ID_APP","DESCRIPTION") USING INDEX;

ALTER TABLE "FWK_CAT_APPS" ADD CONSTRAINT "PK_CUPS_FWK_CAT_APPS" PRIMARY KEY ("ID_APP") USING INDEX;
ALTER TABLE "FWK_CAT_APPS" ADD CONSTRAINT "UQ_CAT_APPS" UNIQUE ("APPLICATION_NAME") USING INDEX;

CREATE INDEX "IXFK_CAT_CONTENT_CAT_ADMIN" ON "FWK_CAT_CONTENT" ("ID_ADMIN") ;
CREATE INDEX "IXFK_CAT_CONTENT_CAT_APPS" ON "FWK_CAT_CONTENT" ("ID_APP") ;
ALTER TABLE "FWK_CAT_CONTENT" ADD CONSTRAINT "PK_CUPS_FWK_CAT_CONTENT" PRIMARY KEY ("ID_CONTENT") USING INDEX;
ALTER TABLE "FWK_CAT_CONTENT" ADD CONSTRAINT "UQ_ADMIN_KEY" UNIQUE ("ID_ADMIN","KEY_VALUE") USING INDEX;
ALTER TABLE "FWK_CAT_CONTENT" ADD CONSTRAINT "UQ_ADMIN_KEY_VALUE" UNIQUE ("ID_ADMIN","KEY_VALUE","VALUE") USING INDEX;

ALTER TABLE "FWK_CORREO_PEND" ADD CONSTRAINT "PK_FWK_CORREO_PEND" PRIMARY KEY ("ID") USING INDEX;
CREATE UNIQUE INDEX "UQ_CORREO_TEMP_NUM_IDIOMA" ON "FWK_CORREO_TEMPLATE" ("NUM_CORREO","ID_IDIOMA") ;
ALTER TABLE "FWK_CORREO_TEMPLATE" ADD CONSTRAINT "CK_FWK_CORREO_TEMP_ESTATUS" CHECK (ESTATUS BETWEEN 0 AND 1);
ALTER TABLE "FWK_CORREO_TEMPLATE" ADD CONSTRAINT "PK_FWK_CORREO_TEMPLATE" PRIMARY KEY ("ID") USING INDEX;

ALTER TABLE "FWK_DBTRACER" ADD CONSTRAINT "PK_FWK_DB_TRACER" PRIMARY KEY ("ID") USING INDEX;

ALTER TABLE "FWK_IDIOMA" ADD CONSTRAINT "PK_FWK_IDIOMA" PRIMARY KEY ("ID") USING INDEX;
ALTER TABLE "FWK_IDIOMA" ADD CONSTRAINT "CK_IDIOMA_ESTATUS" CHECK (Estatus BETWEEN 0 AND 1);
ALTER TABLE "FWK_IDIOMA" ADD CONSTRAINT "UQ_IDIOMA_PAIS" UNIQUE ("COD_IDIOMA","COD_PAIS") USING INDEX;

ALTER TABLE "FWK_CADENA_IDIOMA" ADD CONSTRAINT "PK_FWK_CADENA_IDIOMA" PRIMARY KEY ("ID") USING INDEX;
ALTER TABLE "FWK_CADENA_IDIOMA" ADD CONSTRAINT "UQ_FWK_CADENA_IDIOMA_CLAVE" UNIQUE ("CLAVE","ID_IDIOMA") USING INDEX;

ALTER TABLE "FWK_LOGGER" ADD CONSTRAINT "PK_FWK_LOGGER" PRIMARY KEY ("ID") USING INDEX;

ALTER TABLE "FWK_PREFERENCIAS_USR" ADD CONSTRAINT "PK_FWK_IDIOMA_USR" PRIMARY KEY ("ID_NUM_CONTROL") USING INDEX;

CREATE UNIQUE INDEX "XPKFRAMEWORK_TINY_URL" ON "FWK_TINY_URL" ("ID"   ASC);
CREATE UNIQUE INDEX "XAK1FRAMEWORK_TINY_URL" ON "FWK_TINY_URL" ("TINY_URL"   ASC);
ALTER TABLE "FWK_TINY_URL" ADD CONSTRAINT  "XPKFRAMEWORK_TINY_URL" PRIMARY KEY ("ID");
ALTER TABLE "FWK_TINY_URL" ADD CONSTRAINT  "XAK1FRAMEWORK_TINY_URL" UNIQUE ("TINY_URL");
ALTER TABLE "FWK_TINY_URL" MODIFY "UN_SOLO_USO" CONSTRAINT  "CHK_UN_SOLO_USO" CHECK ("UN_SOLO_USO" BETWEEN 0 AND 1);
ALTER TABLE "FWK_TINY_URL" MODIFY "USADO" CONSTRAINT  "CHK_USADO" CHECK ("USADO" BETWEEN 0 AND 1);
ALTER TABLE "FWK_TINY_URL" MODIFY "EXPIRA" CONSTRAINT  "CHK_EXPIRA" CHECK ("EXPIRA" BETWEEN 0 AND 1);


/* Create Foreign Key Constraints */
ALTER TABLE "SEG_PERFIL_USR" ADD CONSTRAINT "FK_SEG_PERFIL_USR_SEG_PERFIL" FOREIGN KEY ("IDPERFIL") REFERENCES "SEG_PERFIL" ("ID");
ALTER TABLE "SEG_PERFIL_USR" ADD CONSTRAINT "FK_SEG_PERFIL_USR_SEG_USUARIO" FOREIGN KEY ("IDUSUARIO") REFERENCES "SEG_USUARIO" ("ID");

ALTER TABLE "SEG_PERMISO_PERFIL" ADD CONSTRAINT "FK_SEG_PERMISO_PERFIL_SEG_PERF" FOREIGN KEY ("IDPERFIL") REFERENCES "SEG_PERFIL" ("ID");
ALTER TABLE "SEG_PERMISO_PERFIL" ADD CONSTRAINT "FK_SEG_PERMISO_PERFIL_SEG_PERM" FOREIGN KEY ("IDPERMISO") REFERENCES "SEG_PERMISO" ("ID");

ALTER TABLE "FWK_ACTION_ITEM" ADD CONSTRAINT "FK_FWK_ACTION_ITEM_SEG_PERMISO" FOREIGN KEY ("ID_PERMISO") REFERENCES "SEG_PERMISO" ("ID");

ALTER TABLE "FWK_CAT_ADMIN" ADD CONSTRAINT "FK_FWK_CAT_ADMIN_FWK_CAT_APPS" FOREIGN KEY ("ID_APP") REFERENCES "FWK_CAT_APPS" ("ID_APP");

ALTER TABLE "FWK_CAT_CONTENT" ADD CONSTRAINT "FK_CAT_CONTENT_CAT_ADMIN" FOREIGN KEY ("ID_ADMIN") REFERENCES "FWK_CAT_ADMIN" ("ID_ADMIN");
ALTER TABLE "FWK_CAT_CONTENT" ADD CONSTRAINT "FK_CAT_CONTENT_CAT_APPS" FOREIGN KEY ("ID_APP") REFERENCES "FWK_CAT_APPS" ("ID_APP");

ALTER TABLE "FWK_CORREO_PEND" ADD CONSTRAINT "FK_CORREO_PEND_CAT_APP" FOREIGN KEY ("APPS_ID") REFERENCES "FWK_CAT_APPS" ("ID_APP");

ALTER TABLE "FWK_CORREO_TEMPLATE" ADD CONSTRAINT "FK_CORREO_TEMPLATE_CAT" FOREIGN KEY ("APPS_ID") REFERENCES "FWK_CAT_APPS" ("ID_APP");
ALTER TABLE "FWK_CORREO_TEMPLATE" ADD CONSTRAINT "FK_CORREO_TEMPLATE_IDIOMA" FOREIGN KEY ("ID_IDIOMA") REFERENCES "FWK_IDIOMA" ("ID");

ALTER TABLE "FWK_CADENA_IDIOMA" ADD CONSTRAINT "FK_CADENA_IDIOMA_IDIOMA" FOREIGN KEY ("ID_IDIOMA") REFERENCES "FWK_IDIOMA" ("ID");

ALTER TABLE "FWK_LOGGER" ADD CONSTRAINT "FK_LOGGER_CAT_APPS" FOREIGN KEY ("APPS_ID") REFERENCES "FWK_CAT_APPS" ("ID_APP");

ALTER TABLE "FWK_PREFERENCIAS_USR" ADD CONSTRAINT "FK_PREFERENCIAS_USR_IDIOMA" FOREIGN KEY ("ID_IDIOMA") REFERENCES "FWK_IDIOMA" ("ID");
