/* Create Triggers for Autonumber Columns */
CREATE OR REPLACE TRIGGER "TRG_SEG_PERFIL_ID" 
	BEFORE INSERT 
	ON "SEG_PERFIL" 
	FOR EACH ROW 
	when (new.ID is null)
	BEGIN 
		SELECT "SEQ_SEG_PERFIL_ID".NEXTVAL 
		INTO :NEW."ID" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_SEG_PERMISO_ID" 
	BEFORE INSERT 
	ON "SEG_PERMISO" 
	FOR EACH ROW 
	when (new.ID is null)
	BEGIN 
		SELECT "SEQ_SEG_PERMISO_ID".NEXTVAL 
		INTO :NEW."ID" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_FWK_ACCESO_USR_ID_ACCESO" 
	BEFORE INSERT 
	ON "FWK_ACCESO_USR" 
	FOR EACH ROW 
	when (new.ID_ACCESO is null)
	BEGIN 
		SELECT "SEQ_FWK_ACCESO_USR_ID".NEXTVAL 
		INTO :NEW."ID_ACCESO" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_FWK_CAT_ADMIN_ID_ADMIN" 
	BEFORE INSERT 
	ON "FWK_CAT_ADMIN" 
	FOR EACH ROW 
	when (new.ID_ADMIN is null)
	BEGIN 
		SELECT "SEQ_FWK_CAT_ADMIN_ID".NEXTVAL 
		INTO :NEW."ID_ADMIN" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_FWK_CAT_APPS_ID_APP" 
	BEFORE INSERT 
	ON "FWK_CAT_APPS" 
	FOR EACH ROW 
	when (new.ID_APP is null)
	BEGIN 
		SELECT "SEQ_FWK_CAT_APPS_ID".NEXTVAL 
		INTO :NEW."ID_APP" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_FWK_CAT_CONTENT_ID_CONTENT" 
	BEFORE INSERT 
	ON "FWK_CAT_CONTENT" 
	FOR EACH ROW 
	when (new.ID_CONTENT is null)
	BEGIN 
		SELECT "SEQ_FWK_CAT_CONTENT_ID".NEXTVAL 
		INTO :NEW."ID_CONTENT" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_FWK_CORREO_PEND_ID" 
	BEFORE INSERT 
	ON "FWK_CORREO_PEND" 
	FOR EACH ROW 
	when (new.ID is null)
	BEGIN 
		SELECT "SEQ_FWK_CORREO_PEND_ID".NEXTVAL 
		INTO :NEW."ID" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_FWK_CORREO_TEMPLATE_ID" 
	BEFORE INSERT 
	ON "FWK_CORREO_TEMPLATE" 
	FOR EACH ROW 
	when (new.ID is null)
	BEGIN 
		SELECT "SEQ_FWK_CORREO_TEMPLATE_ID".NEXTVAL 
		INTO :NEW."ID" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_FWK_DBTRACER_ID" 
	BEFORE INSERT 
	ON "FWK_DBTRACER" 
	FOR EACH ROW 
	when (new.ID is null)
	BEGIN 
		SELECT "SEQ_FWK_DBTRACER_ID".NEXTVAL 
		INTO :NEW."ID" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_FWK_CADENA_IDIOMA_ID" 
	BEFORE INSERT 
	ON "FWK_CADENA_IDIOMA" 
	FOR EACH ROW 
	when (new.ID is null)
	BEGIN 
		SELECT "SEQ_FWK_CADENA_IDIOMA_ID".NEXTVAL 
		INTO :NEW."ID" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_FWK_TINY_URL_ID" 
	BEFORE INSERT 
	ON "FWK_TINY_URL" 
	FOR EACH ROW 
	when (new.ID is null)
	BEGIN 
		SELECT "SEQ_FWK_TINY_URL_ID".NEXTVAL 
		INTO :NEW."ID" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_FWK_LAYOUT_CARGA_ID" 
	BEFORE INSERT 
	ON "FWK_LAYOUT_CARGA" 
	FOR EACH ROW 
	when (new.ID is null)
	BEGIN 
		SELECT "SEQ_FWK_LAYOUT_CARGA_ID".NEXTVAL 
		INTO :NEW."ID" 
		FROM DUAL; 
	END;
/

CREATE OR REPLACE TRIGGER "TRG_FWK_LAYOUT_POSICIONES_ID" 
	BEFORE INSERT 
	ON "FWK_LAYOUT_POSICIONES" 
	FOR EACH ROW 
	when (new.ID is null)
	BEGIN 
		SELECT "SEQ_FWK_LAYOUT_POSICIONES_ID".NEXTVAL 
		INTO :NEW."ID" 
		FROM DUAL; 
	END;
/
