
CREATE TABLE SEG_PERFIL
( 
	ID                   numeric(5)  IDENTITY ( 1,1 )  NOT NULL ,
	ID_PERFIL_PADRE      numeric(5)  NULL ,
	PERFIL               varchar(50)  NOT NULL ,
	ESTATUS              numeric(1)  NOT NULL 
	CONSTRAINT Default_1_86594819
		 DEFAULT  1
	CONSTRAINT VALORLOGICO_722076729
		CHECK  ( ESTATUS BETWEEN 0 AND 1 ),
	DESCRIPCION          varchar(255)  NULL ,
	ES_PERFIL_MAESTRO    numeric(1)  NOT NULL 
	CONSTRAINT Default_0_98485736
		 DEFAULT  0
	CONSTRAINT VALORLOGICO_1678768914
		CHECK  ( ES_PERFIL_MAESTRO BETWEEN 0 AND 1 ),
	FECHA_CREACION       datetime  NOT NULL ,
	USR_CREACION         varchar(20)  NOT NULL ,
	FECHA_ACTUALIZACION  datetime  NULL ,
	USR_ACTUALIZA        varchar(20)  NULL 
);

ALTER TABLE SEG_PERFIL
	ADD CONSTRAINT XPKSEG_PERFIL3CAB1599_4728BA23 PRIMARY KEY  NONCLUSTERED (ID ASC);

ALTER TABLE SEG_PERFIL
	ADD CONSTRAINT XAK1SEG_PERFIL3CAB1599_4728BA2 UNIQUE (PERFIL  ASC);

CREATE TABLE SEG_PERFIL_USR
( 
	IDUSUARIO                numeric(10)  NOT NULL ,
	IDPERFIL             numeric(5)  NOT NULL 
);

ALTER TABLE SEG_PERFIL_USR
	ADD CONSTRAINT XPKSEG_PERFIL_USRA585167F_465D PRIMARY KEY  NONCLUSTERED (IDUSUARIO ASC,IDPERFIL ASC);

CREATE TABLE SEG_PERMISO
( 
	ID                   numeric(10)  IDENTITY ( 1,1 )  NOT NULL ,
	PERMISO              varchar(150)  NOT NULL ,
	ESTATUS              numeric(1)  NOT NULL 
	CONSTRAINT Default_1_410011157
		 DEFAULT  1
	CONSTRAINT VALORLOGICO_471603072
		CHECK  ( ESTATUS BETWEEN 0 AND 1 ),
	MOSTRARENMENU        numeric(1)  NOT NULL 
	CONSTRAINT CK_PERMISO_MOSTRARMENU
		 DEFAULT  0
	CONSTRAINT VALORLOGICO_2034460229
		CHECK  ( MOSTRARENMENU BETWEEN 0 AND 1 ),
	DESCRIPCION          varchar(255)  NULL 
);

ALTER TABLE SEG_PERMISO
	ADD CONSTRAINT XPKSEG_PERMISOF51FE4A8_4F24A35 PRIMARY KEY  NONCLUSTERED (ID ASC);

ALTER TABLE SEG_PERMISO
	ADD CONSTRAINT XAK1SEG_PERMISOF51FE4A8_4F24A3 UNIQUE (PERMISO  ASC);

CREATE TABLE SEG_PERMISO_PERFIL
( 
	IDPERFIL             numeric(5)  NOT NULL ,
	IDPERMISO            numeric(10)  NOT NULL 
);

ALTER TABLE SEG_PERMISO_PERFIL
	ADD CONSTRAINT XPKSEG_PERMISO_PERFIL983CEF1F_ PRIMARY KEY  NONCLUSTERED (IDPERFIL ASC,IDPERMISO ASC);

CREATE TABLE SEG_USUARIO
( 
	ID                   numeric(10)  NOT NULL ,
	USER_ID              varchar(20)  NOT NULL ,
	NOMBREUSUARIO            varchar(75)  NULL ,
	APPATERNO            varchar(75)  NULL ,
	APMATERNO            varchar(75)  NULL ,
	CORREOE              varchar(100)  NULL ,
	ESTATUS              numeric(1)  NOT NULL 
	CONSTRAINT Default_1_209603096
		 DEFAULT  1
	CONSTRAINT VALORLOGICO_538905486
		CHECK  ( ESTATUS BETWEEN 0 AND 1 ),
	FECHA_CREACION       datetime  NOT NULL ,
	USR_CREACION         varchar(20)  NOT NULL ,
	FECHA_ACTUALIZACION  datetime  NULL ,
	USR_ACTUALIZA        varchar(20)  NULL 
);

ALTER TABLE SEG_USUARIO
	ADD CONSTRAINT XPKSEG_USUARIO67BB99C8_427F745 PRIMARY KEY  NONCLUSTERED (ID ASC);

ALTER TABLE SEG_USUARIO
	ADD CONSTRAINT XAK1SEG_USUARIO67BB99C8_427F74 UNIQUE (USER_ID  ASC);

CREATE TABLE SEG_VACATION_MODE
( 
	ID                   numeric(10)  IDENTITY ( 1,1 )  NOT NULL ,
	ID_USR_OTORGA        numeric(10)  NOT NULL ,
	ID_USR_RECIBE        numeric(10)  NULL ,
	FECHA_INICIAL        datetime  NOT NULL ,
	FECHA_FINAL          datetime  NULL ,
	ESTATUS              numeric(1)  NOT NULL 
	CONSTRAINT Default_1_2001953842
		 DEFAULT  1,
	FECHA_CREACION       datetime  NOT NULL ,
	USR_CREACION         varchar(20)  NOT NULL ,
	FECHA_ACTUALIZACION  datetime  NULL ,
	USR_ACTUALIZA        varchar(20)  NULL ,
	ID_PERFIL_OTORGA     numeric(5)  NOT NULL
);

ALTER TABLE SEG_VACATION_MODE
	ADD CONSTRAINT XPKSEG_VACATION_MODED7344CC8_4 PRIMARY KEY  NONCLUSTERED (ID ASC);


ALTER TABLE SEG_PERFIL
	ADD CONSTRAINT FK_SEG_PERFIL_SEG_PERFIL_4E624 FOREIGN KEY (ID_PERFIL_PADRE) REFERENCES SEG_PERFIL(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;


ALTER TABLE SEG_PERFIL_USR
	ADD CONSTRAINT FK_SEG_PERFIL_USR_SEG_USUAR336 FOREIGN KEY (IDUSUARIO) REFERENCES SEG_USUARIO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE SEG_PERFIL_USR
	ADD CONSTRAINT FK_SEG_PERFIL_USR_SEG_PERFIF42 FOREIGN KEY (IDPERFIL) REFERENCES SEG_PERFIL(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;


ALTER TABLE SEG_PERMISO_PERFIL
	ADD CONSTRAINT FK_SEG_PERMISO_PERFIL_SEG_P416 FOREIGN KEY (IDPERFIL) REFERENCES SEG_PERFIL(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE SEG_PERMISO_PERFIL
	ADD CONSTRAINT FK_SEG_PERMISO_PERFIL_SEG_P246 FOREIGN KEY (IDPERMISO) REFERENCES SEG_PERMISO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;


ALTER TABLE SEG_VACATION_MODE
	ADD CONSTRAINT FK_SEG_VACATION_MODE_SEG_US2BB FOREIGN KEY (ID_USR_OTORGA) REFERENCES SEG_USUARIO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE SEG_VACATION_MODE
	ADD CONSTRAINT FK_SEG_VACATION_MODE_SEG_US405 FOREIGN KEY (ID_USR_RECIBE) REFERENCES SEG_USUARIO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;
		
ALTER TABLE SEG_VACATION_MODE
	ADD CONSTRAINT FK_SEG_VACATION_MODE_SEG_PERFIL_OTORGA FOREIGN KEY (ID_PERFIL_OTORGA) REFERENCES SEG_PERFIL(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;
