
CREATE TABLE APROBACION_CONFIGURA_FLUJO
( 
	ID                   numeric(8)  IDENTITY ( 1,1 )  NOT NULL ,
	ID_PROCESO           numeric(5)  NOT NULL ,
	NOMBRE_FLUJO         varchar(75)  NOT NULL ,
	ESTATUS              numeric(1)  NOT NULL 
	CONSTRAINT Default_1_1161788229
		 DEFAULT  1,
	FECHA_CREACION       datetime  NOT NULL ,
	USR_CREACION         varchar(20)  NOT NULL ,
	FECHA_ACTUALIZACION  datetime  NULL ,
	USR_ACTUALIZA        varchar(20)  NULL ,
	CODIGO_FLUJO         varchar(20)  NOT NULL ,
	ID_ESTADO_PROCESO_APROBADO numeric(5)  NOT NULL ,
	ID_ESTADO_PROCESO_RECHAZADO numeric(5)  NOT NULL ,
	ID_PANTALLA_EJECUTAR numeric(5)  NOT NULL 
);

ALTER TABLE APROBACION_CONFIGURA_FLUJO
	ADD CONSTRAINT XPKAPROBACION_CONFIGURA_FLUF1A PRIMARY KEY  NONCLUSTERED (ID ASC);

ALTER TABLE APROBACION_CONFIGURA_FLUJO
	ADD CONSTRAINT XAK1APROBACION_CONFIGURA_FLUF1 UNIQUE (ID_PROCESO  ASC);

ALTER TABLE APROBACION_CONFIGURA_FLUJO
	ADD CONSTRAINT XAK2APROBACION_CONFIGURA_FLUF1 UNIQUE (CODIGO_FLUJO  ASC);

CREATE TABLE APROBACION_CONFIGURA_FLUJO_DET
( 
	ID                   numeric(8)  IDENTITY ( 1,1 )  NOT NULL ,
	ID_NODO_PADRE        numeric(8)  NULL ,
	ID_FLUJO             numeric(8)  NOT NULL ,
	CANTIDAD_AUTORIZADORES_MINIMO numeric(2)  NOT NULL ,
	CANTIDAD_AUTORIZADORES_MAXIMO numeric(2)  NOT NULL ,
	ID_PERFIL_APROBADOR  numeric(5)  NOT NULL ,
	ESTATUS              numeric(1)  NOT NULL 
	CONSTRAINT Default_1_1534869351
		 DEFAULT  1,
	FECHA_CREACION       datetime  NOT NULL ,
	USR_CREACION         varchar(20)  NOT NULL ,
	FECHA_ACTUALIZACION  datetime  NULL ,
	USR_ACTUALIZA        varchar(20)  NULL ,
	EVIDENCIA_OBLIGATORIA numeric(1)  NOT NULL 
	CONSTRAINT Default_0_1616730234
		 DEFAULT  0
	CONSTRAINT VALORLOGICO_2106498738
		CHECK  ( EVIDENCIA_OBLIGATORIA BETWEEN 0 AND 1 ),
	ID_USR_DEBE_APROBAR  numeric(10)  NULL ,
	NODO_APROBACION_OBLIGATORIA numeric(1)  NOT NULL 
	CONSTRAINT Default_1_969547573
		 DEFAULT  1
	CONSTRAINT VALORLOGICO_180602663
		CHECK  ( NODO_APROBACION_OBLIGATORIA BETWEEN 0 AND 1 )
);

ALTER TABLE APROBACION_CONFIGURA_FLUJO_DET
	ADD CONSTRAINT XPKAPROBACION_CONFIGURA_FLUB80 PRIMARY KEY  NONCLUSTERED (ID ASC);

CREATE TABLE APROBACION_DETALLE_EVIDENCIA
( 
	ID                   numeric(8)  IDENTITY ( 1,1 )  NOT NULL ,
	ID_PROPIETARIO       numeric(8)  NOT NULL ,
	ID_DOCUMENTO         numeric(12)  NOT NULL 
);

ALTER TABLE APROBACION_DETALLE_EVIDENCIA
	ADD CONSTRAINT XPKAPROBACION_DETALLE_EVIDEE5D PRIMARY KEY  NONCLUSTERED (ID ASC);

CREATE TABLE APROBACION_REGISTRO
( 
	ID                   numeric(8)  IDENTITY ( 1,1 )  NOT NULL ,
	ID_PROCESO           numeric(5)  NOT NULL ,
	ID_ESTADO_PROCESO    numeric(5)  NOT NULL ,
	ESTATUS              numeric(1)  NOT NULL 
	CONSTRAINT Default_1_1443896903
		 DEFAULT  1,
	FECHA_CREACION       datetime  NOT NULL ,
	USR_CREACION         varchar(20)  NOT NULL ,
	FECHA_ACTUALIZACION  datetime  NULL ,
	USR_ACTUALIZA        varchar(20)  NULL ,
	ID_PANTALLA_EJECUTAR numeric(5)  NOT NULL ,
	ID_PROPIETARIO       numeric(12)  NOT NULL 
);

ALTER TABLE APROBACION_REGISTRO
	ADD CONSTRAINT XPKAPROBACION_REGISTROC6ABA2A1 PRIMARY KEY  NONCLUSTERED (ID ASC);

CREATE TABLE APROBACION_REGISTRO_DETALLE
( 
	ID                   numeric(8)  IDENTITY ( 1,1 )  NOT NULL ,
	ID_APROBADOR_PADRE   numeric(8)  NULL ,
	ID_PROCESO_APROBACION numeric(8)  NOT NULL ,
	ORDEN                numeric(2)  NOT NULL ,
	ES_OPCIONAL          numeric(1)  NOT NULL 
	CONSTRAINT Default_0_1800421201
		 DEFAULT  0
	CONSTRAINT VALORLOGICO_1766353985
		CHECK  ( ES_OPCIONAL BETWEEN 0 AND 1 ),
	ID_PERFIL_DEBE_APROBAR numeric(5)  NOT NULL ,
	ID_PERFIL_EVALUA     numeric(5)  NULL ,
	APROBADO             numeric(1)  NOT NULL 
	CONSTRAINT Default_0_1618773580
		 DEFAULT  0
	CONSTRAINT VALORLOGICO_1549033356
		CHECK  ( APROBADO BETWEEN 0 AND 1 ),
	RECHAZADO            numeric(1)  NOT NULL 
	CONSTRAINT Default_0_1636729478
		 DEFAULT  0
	CONSTRAINT VALORLOGICO_1485725854
		CHECK  ( RECHAZADO BETWEEN 0 AND 1 ),
	FECHA_EVALUACION     datetime  NULL ,
	ID_ESTADO_PROCESO    numeric(5)  NOT NULL ,
	ID_MOTIVO_RECHAZO    numeric(5)  NULL ,
	ESTATUS              numeric(1)  NOT NULL 
	CONSTRAINT Default_1_1249932115
		 DEFAULT  1,
	FECHA_CREACION       datetime  NOT NULL ,
	USR_CREACION         varchar(20)  NOT NULL ,
	FECHA_ACTUALIZACION  datetime  NULL ,
	USR_ACTUALIZA        varchar(20)  NULL ,
	ID_USR_DEBE_APROBAR  numeric(10)  NULL ,
	ID_USR_EVALUA        numeric(10)  NULL ,
	NODO_APROBACION_OBLIGATORIA numeric(1)  NOT NULL 
	CONSTRAINT Default_1_540618258
		 DEFAULT  1
	CONSTRAINT VALORLOGICO_1477058858
		CHECK  ( NODO_APROBACION_OBLIGATORIA BETWEEN 0 AND 1 ),
	EVIDENCIA_OBLIGATORIA numeric(1)  NOT NULL 
	CONSTRAINT Default_0_1381780867
		 DEFAULT  0
	CONSTRAINT VALORLOGICO_596332908
		CHECK  ( EVIDENCIA_OBLIGATORIA BETWEEN 0 AND 1 ),
	OBSERVACIONES_EVALUADOR varchar(200)  NULL 
);

ALTER TABLE APROBACION_REGISTRO_DETALLE
	ADD CONSTRAINT XPKAPROBACION_REGISTRO_DETAFBD PRIMARY KEY  NONCLUSTERED (ID ASC);


ALTER TABLE APROBACION_CONFIGURA_FLUJO
	ADD CONSTRAINT FK_APROBACION_CONFIGURA_FLU80E FOREIGN KEY (ID_PROCESO) REFERENCES CATALOGO_PROCESO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_CONFIGURA_FLUJO
	ADD CONSTRAINT FK_APROBACION_CONFIGURA_FLU985 FOREIGN KEY (ID_ESTADO_PROCESO_APROBADO) REFERENCES CATALOGO_ESTADOS_PROCESO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_CONFIGURA_FLUJO
	ADD CONSTRAINT FK_APROBACION_CONFIGURA_FLU67C FOREIGN KEY (ID_ESTADO_PROCESO_RECHAZADO) REFERENCES CATALOGO_ESTADOS_PROCESO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_CONFIGURA_FLUJO
	ADD CONSTRAINT FK_APROBACION_CONFIGURA_FLU856 FOREIGN KEY (ID_PANTALLA_EJECUTAR) REFERENCES FWK_CATALOGO_PANTALLAS(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;


ALTER TABLE APROBACION_CONFIGURA_FLUJO_DET
	ADD CONSTRAINT FK_APROBACION_CONFIGURA_FLU245 FOREIGN KEY (ID_FLUJO) REFERENCES APROBACION_CONFIGURA_FLUJO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_CONFIGURA_FLUJO_DET
	ADD CONSTRAINT FK_APROBACION_CONFIGURA_FLU5CB FOREIGN KEY (ID_NODO_PADRE) REFERENCES APROBACION_CONFIGURA_FLUJO_DET(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_CONFIGURA_FLUJO_DET
	ADD CONSTRAINT FK_APROBACION_CONFIGURA_FLU9F3 FOREIGN KEY (ID_PERFIL_APROBADOR) REFERENCES SEG_PERFIL(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_CONFIGURA_FLUJO_DET
	ADD CONSTRAINT FK_APROBACION_CONFIGURA_FLU20E FOREIGN KEY (ID_USR_DEBE_APROBAR) REFERENCES SEG_USUARIO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;


ALTER TABLE APROBACION_DETALLE_EVIDENCIA
	ADD CONSTRAINT FK_APROBACION_DETALLE_EVIDE187 FOREIGN KEY (ID_PROPIETARIO) REFERENCES APROBACION_REGISTRO_DETALLE(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_DETALLE_EVIDENCIA
	ADD CONSTRAINT FK_APROBACION_DETALLE_EVIDEE47 FOREIGN KEY (ID_DOCUMENTO) REFERENCES CM_DOCUMENTO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;


ALTER TABLE APROBACION_REGISTRO
	ADD CONSTRAINT FK_APROBACION_REGISTRO_CATACF3 FOREIGN KEY (ID_PROCESO) REFERENCES CATALOGO_PROCESO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_REGISTRO
	ADD CONSTRAINT FK_APROBACION_REGISTRO_CATAFB8 FOREIGN KEY (ID_ESTADO_PROCESO) REFERENCES CATALOGO_ESTADOS_PROCESO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_REGISTRO
	ADD CONSTRAINT FK_APROBACION_REGISTRO_FWK_F99 FOREIGN KEY (ID_PANTALLA_EJECUTAR) REFERENCES FWK_CATALOGO_PANTALLAS(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;


ALTER TABLE APROBACION_REGISTRO_DETALLE
	ADD CONSTRAINT FK_APROBACION_REGISTRO_DETA843 FOREIGN KEY (ID_PROCESO_APROBACION) REFERENCES APROBACION_REGISTRO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_REGISTRO_DETALLE
	ADD CONSTRAINT FK_APROBACION_REGISTRO_DETA63D FOREIGN KEY (ID_APROBADOR_PADRE) REFERENCES APROBACION_REGISTRO_DETALLE(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_REGISTRO_DETALLE
	ADD CONSTRAINT FK_APROBACION_REGISTRO_DETA16A FOREIGN KEY (ID_PERFIL_DEBE_APROBAR) REFERENCES SEG_PERFIL(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_REGISTRO_DETALLE
	ADD CONSTRAINT FK_APROBACION_REGISTRO_DETA422 FOREIGN KEY (ID_PERFIL_EVALUA) REFERENCES SEG_PERFIL(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_REGISTRO_DETALLE
	ADD CONSTRAINT FK_APROBACION_REGISTRO_DETA877 FOREIGN KEY (ID_ESTADO_PROCESO) REFERENCES CATALOGO_ESTADOS_PROCESO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_REGISTRO_DETALLE
	ADD CONSTRAINT FK_APROBACION_REGISTRO_DETA232 FOREIGN KEY (ID_MOTIVO_RECHAZO) REFERENCES CATALOGO_MOTIVOS_RECHAZO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_REGISTRO_DETALLE
	ADD CONSTRAINT FK_APROBACION_REGISTRO_DETA264 FOREIGN KEY (ID_USR_DEBE_APROBAR) REFERENCES SEG_USUARIO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE APROBACION_REGISTRO_DETALLE
	ADD CONSTRAINT FK_APROBACION_REGISTRO_DETA330 FOREIGN KEY (ID_USR_EVALUA) REFERENCES SEG_USUARIO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;
