insert into FWK_CAT_ADMIN (Id_App,Description,Status) values ((select id_app from FWK_CAT_APPS where Application_Name = 'BASE_APP'),'ThemesList',1);

--Creacion de lista de temas
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'afterdark',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'afternoon',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'afterwork',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'aristo',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'black-tie',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'blitzer',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'bluesky',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'bootstrap',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'casablanca',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'cupertino',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'cruze',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'dark-hive',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'delta',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'dot-luv',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'eggplant',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'excite-bike',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'flick',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'glass-x',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'home',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'hot-sneaks',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'humanity',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'le-frog',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'midnight',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'mint-choc',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'omega',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'overcast',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'pepper-grinder',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'redmond',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'rocket',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'sam',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'smoothness',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'south-street',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'start',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'sunny',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'swanky-purse',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'trontastic',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'ui-darkness',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'ui-lightness',1);
insert into fwk_cat_content (id_app,id_admin,key_value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'vader',1);

update fwk_cat_content set value = key_value where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and id_admin = (select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList');

insert into fwk_cat_content (id_app,id_admin,key_value,value,status) values ((select id_app from fwk_Cat_apps where application_name = 'BASE_APP'),(select id_admin from fwk_Cat_admin where id_app = (select id_app from fwk_Cat_apps where application_name = 'BASE_APP') and description = 'ThemesList'),'vw-theme-petrol','Volkswagen México - Petróleo',1);
