ID_IDIOMA^CLAVE^VALOR
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.OPCIONES^Options
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.FAVORITOS^Favorites
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CHOOSEMENUPOS^Menu position
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.COLUMNAS^Columns
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^0.MOD1_300^System error number 300 on system 0 module 1
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^1.ETIQUETA_001^The key value can''t be repeated
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^1.MAIL_001^Mail server authentication failed.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^1.MAIL_002^Without connection to mail server, saving mail for sending later.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^1.MAIL_003^Exception occurred during mail sending, please verify log.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^1.MAIL_004^Error occurred when saving to database.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^1.MAIL_005^File for attachment not found.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^1.MOD1_300^System error number 300 on system 1 module 1
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^1.PERFIL_001^No se permiten nombres duplicados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^1.PERMISO_001^No se permiten nombres duplicados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^1.PERMISO_002^No fue posible realizar la asignaci�n de permisos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^1.VALIDA_00^The fields: {0}, are required, please give them a value.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.CAT_01^The application [1] is already registered.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.CAT_02^The catalog [1] is already registered for application [2].
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.EXC_001^Error occurred during SQL execution.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.EXC_002^Database connection error.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.EXC_003^Malformed query:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.EXC_004^Sent data error for query:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.EXC_005^The query generates referential integrity error:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.EXC_006^Can''t acquire database lock:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.GEN_000^System error occurred:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.MAIL_001^Mail server authentication failed.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.MAIL_002^Without connection to mail server, saving mail for sending later.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.MAIL_003^Exception occurred during mail sending, please verify log.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.MAIL_004^Error occurred when saving to database.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.MAIL_005^File for attachment not found.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^2.MOD1_100^Error occurred when processing file: [NomArchivo]
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.ACTIVA.HEADER^Enable e-mail
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.ACTIVA.MSGCONFIRMA^Are you sure to enable e-mail?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.BCC^BCC
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.BCC.VALIDFORMAT^BCC field format is wrong
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.CC^CC
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.CC.VALIDFORMAT^CC field format is wrong
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.HEADER^E-Mail Information
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.MENSAJE^Message
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.MSJ.REQUIRED^Message field is required
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.NUMERO.REQUIRED^Number field is required
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.SISTEMA^System
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.SUBJECT^Subject
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.SUBJECT.REQUIRED^Subject field is required
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.SUBJECT.VALIDFORMAT^Subject fiels is wrong
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.TO^TO
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DATA.TO.VALIDFORMAT^TO field is wrong
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DESACTIVA.HEADER^Disable e-mail
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.DESACTIVA.MSGCONFIRMA^Are you sure to disable e-mail?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.FILTRO.HEADER^Show e-mails from
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.NUMERO^Number
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.REPORTE.NOMBRE^e-mail report
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.TEMPLATE.TITULO^eMail Template Configuration
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.TITULO^Send test eMails
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^CORREO.UPDATE.HEADER^New e-mail
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^ERROR_NO_CATALOGADO^Not classified in system.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^ETIQUETA.DATA.CLAVE^Key
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^ETIQUETA.DATA.CLAVE.REQUIRED^The chain field is required 
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^ETIQUETA.DATA.VALOR^Predefined language value
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^ETIQUETA.DATA.VALOR.REQUIRED^The value field is required 
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^ETIQUETA.NEW.HEADER^New chain
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ABAJO^Down
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ACCESS.ERRORMSG^You don''t have permission to run this page
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ACCESS.HEADER^Access error
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ACEPTAR^Accept
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ACTIVA^Enable
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ADD^Add
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.AMBIENTE.DESARROLLO^DEV
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.AMBIENTE.INTEGRACION^INTEGRA
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.AMBIENTE.QA^QAS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ARRIBA^Up
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.AUTORIZA^Authorize
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.AYUDA^Help
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.AYUDA.GRAL^General
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.AYUDA.MANUALUSR^Usr. Man.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.BUSCAR^Find
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CADENAS^System Strings
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CADENAS.CLAVE^Key
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CADENAS.IDIOMA^Language
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CADENAS.MESSAGES^Registered Messages
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CADENAS.STRINGS^Registered Strings
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CADENAS.VALOR^Value
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CADENAS.VALORESPARA^Values for
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CANCELAR^Cancel
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CHOOSELANG^Choose your language
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CONFIRMA.HEADER^Please confirm
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.CONFIRMA.MSGCONFIRMA^Are you sure of your action?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.DATA.ALL^All
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.DATA.ACTIVO^Active
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.DATA.ESTATUS^Status
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.DATA.FALSE^No
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.DATA.INACTIVO^Inactive
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.DATA.TRUE^Yes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.DETALLE^Detail
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.EDITAR^Edit
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ELIMINAR^Delete
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.EMPTYMESSAGE^No records found with provided filter
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ERROR.HANDLER.CLASS^Exception Class
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ERROR.HANDLER.CODE^Error Code
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ERROR.HANDLER.DESC^Error Description
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ERROR.HANDLER.STACK^Request StackTrace
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ERROR.HANDLER.TITLE^Error Handling - Error Detected
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ERROR.HANDLER.TYPE^Exception Type
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ERROR.HANDLER.URI^Request URI
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.EXCEL^XLS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.EXIT^Exit
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.EXPLORER.ERRORMSG^This application requires Mozilla FireFox, impossible to continue
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.EXPORT.ALL^Export all
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.EXPORT.PAGE^Export page
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.EXPORT.PRINT^Print
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.EXPORTAR^Export
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.FILELOADER.ERROR^Error on line: %s | Attribute: %s | IniPos: %s | EndPos: %s | Error: %s
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.FILTER.WAIT.MESSAGE^Please wait, your query is being executed.....
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.GUARDAR^Save
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ID^ID
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.IMAGE.SAVE^Right click mouse and choose ''Save image''
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.IMAGEN^Image
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.IMPRIMIR^Print
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.INACTIVA^Disable
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.LIBERAR^Free
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.MENSAJES.TITULO^Messages
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.MESSAGES^System Messages
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.MOSTRAR^Show
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.MOSTRAR.IRPAGINA^Go to Page:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.MOSTRAR.PAGINA^Page
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.MOSTRAR.PAGINA.ROWS^1,2,3,4,5,10,15,20,25,50,75,100
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.MOSTRAR.PAGINA.X.DE.Y^of
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.MOSTRAR_REGS_PREFIJO^Show
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.MOSTRAR_REGS_SUFIJO^records.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.MOUSE.RIGHTBUTTON.MSG^You can''t use right mouse button
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.NOMBREMES^January,February,March,April,May,June,July,August,September,October,November,December
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.NOMBREMESABREV^JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DIC
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.NUEVO^New
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.OPTS.ALL^All...
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.PAGINATOR.CURRROWTEMPLATE^Page: ({currentPage} of {totalPages})
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.PAGINATOR.TEMPLATE^{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {CurrentPageReport} Show {RowsPerPageDropdown} records.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.PAGINATOR.TEMPLATE.NONUMROWS^{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {CurrentPageReport}
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.PDF^PDF
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.REPORTE.AUTOR^Software Factory
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.REPORTE.SISTEMA^ADAN System
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.RESIZE^Adjust
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.RESIZE.MESSAGE^Execute your query to update the view
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.SAVE.EXITO^Information succesfully saved.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.SEARCH.ALLFIELDS^Find in all
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.SEARCH.ALLFIELDS.KEY^Register a value...
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.SELECCIONAR^Choose
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.SESSION.MESSAGE.CONTINUE^Do you want to extend your session?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.SESSION.MESSAGE.POST^seconds.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.SESSION.MESSAGE.PRE^You will be redirected out of the system in
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.SESSION.TITLE^Your session is about to expire!
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.SWF^Software Factory
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.TITULO^ADAN System
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.AVANCE^Progress
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.CANCEL^Cancel
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.CHOOSE^Choose...
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.FASE^Phase
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.FASE.X.DE.Y^of
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.FILES^1
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.HEADER^File Upload
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.LIMITMESSAGE^You can upload 1 file at a time
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.LIMITSIZE^102400
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.SIZEMESSAGE^You can upload files with size less than 100kb
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.STATUS.TITLE^Process progress
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.TYPEMESSAGE^You can upload files of type gif, jpg, png, txt, csv, xls, zip, rar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.TYPES^gif|jpe?g|png|txt|csv|xls|zip|rar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.UPLOAD.UPLOAD^Upload
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.VERSION.LABEL^Version
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.VERSION.NUM^1.0.0
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.VISTAPRELIMINAR^Preview
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ZOOM^Resize
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.ACTIVA.HEADER^Please confirm
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.ACTIVA.MSGCONFIRMA^Are you sure to activate the language?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DATA.CODIDIOMA^Language Code
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DATA.CODIDIOMA.REQUIRED^The language code is required
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DATA.CODIDIOMA.VALIDFORMAT^The language code only accepts two lowercase letters
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DATA.CODPAIS^Country Code
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DATA.CODPAIS.REQUIRED^The country code is required
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DATA.CODPAIS.VALIDFORMAT^The country code accepts only two capital letters
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DATA.HEADER^Language Administration
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DATA.IDIOMA^Language
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DATA.IDIOMA.REQUIRED^The attribute language is required , please provide the value
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DATA.IDIOMA.VALIDFORMAT^The attribute language does not have the correct format
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DATA.PREDETERMINADO^Default language
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DESACTIVA.HEADER^Please confirm
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.DESACTIVA.MSGCONFIRMA^Are you sure to disable the language?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.REPORTE.NOMBRE^Languages 
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.TITULO^Language Administration
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^IDIOMA.UPDATE.HEADER^Update Language
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Administracion^Administration
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Catalogo^Simple catalogs
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.ConfiguracionAMS^Configuration for AMS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Estadistica^Statistics
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Idioma^Languages
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Inicio^Home
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Menu^Options menu
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Parametro^Parameters
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Perfil^Profiles
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Permiso^Permissions
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Principal^Common used
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Proceso^Processes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Reporte^Reports
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Salir^Exit
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Seguridad^Security
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENU.Template^Mail templates
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.ACTIVA.HEADER^Enable
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.ACTIVA.MSGCONFIRMA^Are you sure to enable menu option
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.DATA.HEADER^Export data
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.DATA.LABEL.REQUIRED^Label field is required
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.DATA.PERMISO.REQUIRED^Permission field is required
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.DELETE.HEADER^Delete option permanently
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.DELETE.MSGCONFIRMA^Are you sure to delete menu option?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.DESACTIVA.HEADER^Disable
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.DESACTIVA.MSGCONFIRMA^Are you sure to disable menu option?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.EDIT^Edit menu options
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.ENABLED^Enabled
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.ICON^Icon Url
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.IDPERMISO^Permission Id
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.LABEL^Label
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.LABEL.PERMISO^Permission
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.LABEL.VALOR^Label value
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.ORDERHINT^Order
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.PARENT^Parent Id
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.REPORTE.NOMBRE^Menu options report
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.TITULO^Menu Options Configuration
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^MENUCONFIG.URL^Url
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.ACTIVA.HEADER^Enable parameter
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.ACTIVA.MSGCONFIRMA^Are you sure to enable parameter?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.CLAVE^Key
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.DATA.CAT^Catalog
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.DATA.GRUPO^Group
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.DATA.HEADER^Configuration parameters
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.DATA.PARAMETRO^Value
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.DATA.PARAMETRO.REQUIRED^Key field is required
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.DATA.PARAMETRO.VALIDFORMAT^The fiel parameter has wrong format
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.DATA.SISTEMA^System
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.DATA.VALOR^Value
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.DESACTIVA.HEADER^Disable parameter
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.DESACTIVA.MSGCONFIRMA^Are you sure to disable parameter?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.DESCRIPCION^Description
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.FILTRO.HEADER^Filter information using
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.REPORTE.NOMBRE^Parameters Report
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.TITULO^Parameters Administration
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PARAMETRO.UPDATE.HEADER^New value
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.ACTIVA.HEADER^Enable profile
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.ACTIVA.MSGCONFIRMA^Are you sure to enable this profile?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.ADD.PERMISO^Add Permissions
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.DATA.HEADER^Registered Profiles
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.DATA.PERFIL^Profile
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.DATA.DESCRIPCION^Description
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.DATA.PERFIL.REQUIRED^The profile field is required
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.DATA.PERFIL.VALIDFORMAT^The profile has wrong format
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.DESACTIVA.HEADER^Disable profile
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.DESACTIVA.MSGCONFIRMA^Are you sure to disable this profile?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.REPORTE.NOMBRE^Profiles Report
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.TITULO^Profile Administration
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERFIL.UPDATE.HEADER^Add or Edit Profile
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.ACTIVA.HEADER^Enable permission
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.ACTIVA.MENU.HEADER^Show in menu configuration
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.ACTIVA.MENU.MSGCONFIRMA^Are you sure to show this permission in menu configuration?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.ACTIVA.MSGCONFIRMA^Are you sure to enable this permission?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.ASIGNAR.HEADER^Assign permission
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.DATA.HEADER^Registered Permissions
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.DATA.MOSTRARENMENU^Show in Menu
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.DATA.PERMISO^Permission
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.DATA.DESCRIPCION^Description
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.DATA.PERMISO.REQUIRED^The permission field is required
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.DATA.PERMISO.VALIDFORMAT^The permission field format is wrong
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.DATA.QUITARENMENU^Hide in menu
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.DESACTIVA.HEADER^Disable permission
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.DESACTIVA.MENU.HEADER^Hide in menu configuration
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.DESACTIVA.MENU.MSGCONFIRMA^Are you sure to hide this permission in menu configuration?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.DESACTIVA.MSGCONFIRMA^Are you sure to disable this permission?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.FILTRO.HEADER^Filter permission using
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.FILTRO.PERFIL^Profile
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.REPORTE.NOMBRE^Permissions Report
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.TITULO^Permission''s Manager
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^PERMISO.UPDATE.HEADER^Add or Modify Permission
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.BEANNAME^Bean name
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.BEANPACKAGE^Bean Package
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.BEANPATH^Bean Path
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.ENTITYNAME^Entity Name
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.ENTITYPACKAGE^Entity path
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.HEAD^Create Simple Catalog
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.JSFNAME^JSF Name
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.JSFPATH^XHTML Path
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.NAME^Catalog name
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.PATH^Workspace Path
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.PROJNAME^Project name
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.PROJPATH^Project Path
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.SERVICENAME^Service Name
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^WIZARD.SIMPLE_CATALOG.SERVICEPACKAGE^Service path
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ACTIVA.HEADER^Enable Record
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.ACTIVA.MSGCONFIRMA^Are you sure to enable this record?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.DESACTIVA.HEADER^Disable Record
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.DESACTIVA.MSGCONFIRMA^Are you sure to disable this record?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GNERAL.RELOAD^Reload
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='en' AND COD_PAIS='US')^GENERAL.SELECCIONE^Choose...
