ID_IDIOMA^CLAVE^VALOR
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SYSTEM.ABREV^BANNER
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SYSTEM.NAME^Banner de Anuncios
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.REPORTE.PUBLICO.SISTEMA^Banner de Anuncios
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.TITULO.PUBLICO^Banner de Anuncios
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.REPORTE.SISTEMA^Banner de Anuncios
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.TITULO^Banner de Anuncios

(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.BUGREPORT^Reportar error
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ICONOS.COPYCODE^Copiar código
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.APARIENCIA^Tema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ICONOS.HEADER^Iconos del sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SHOWLOG^Mostrar Log
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.TODOS^Todos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SELECCIONE^Seleccione...
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.IDENTIFICADOR^Identificador
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.GENERO^Género
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.EXPIRED.RELOAD^Se acabó el tiempo disponible para las consultas, por favor ingrese nuevamente a la página deseada.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.FAVORITOS.LIMITE^Solo se permite tener 10 favoritos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.OPCIONES^Opciones
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.FAVORITOS^Favoritos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CHOOSETHEME^Seleccionar Tema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CHOOSETEMPLATE^Template
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CHOOSEMENUPOS^Posición de Menú
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CERRAR^Cerrar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.MODIFICADOEN^Fecha Modificación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ELEGIR^Seleccionar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.COLUMNAS^Columnas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.APP.CONFIG.ERROR^Error de Configuración
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.NO^NO
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.SI^SI
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.NO.MAYUSC^NO
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.SI.MAYUSC^SI
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.FECHACREACION^Fecha Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.USRCREACION^Usuario Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.FECHAACTUALIZACION^Fecha Actualización
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.USRACTUALIZA^Usuario Actualiza
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.REGRESAR^Regresar 
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.GUARDAR.MSGCONFIRMA^¿Está seguro que desea guardar el registro?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CONFIRMACION.TITULO^Confirmación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DESACTIVA.ETIQUETA^Desactivar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TEMPLATE.GENERAL^Template Predeterminado
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TEMPLATE.MENUMOVIL^Template con menú móvil
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.COOKIES.HEADER^Error de Configuración
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.COOKIES.ERRORMSG^Su navegador no tiene habilitado el uso de cookies y es necesario para la aplicación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^0.MOD1_300^Mensaje 300 del sistema 0 Módulo 1
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^1.ETIQUETA_001^La clave no se puede repetir
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^1.MAIL_001^Falló la autenticación en servidor de correo.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^1.MAIL_002^Sin conexión a servidor de correo, guardando correo para envío posterior.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^1.MAIL_003^Ocurrió una excepción en el envío de correo, favor de revisar el log.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^1.MAIL_004^Ocurrió un error al escribir en la Base de Datos.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^1.MAIL_005^No se encontró el archivo para adjuntar al correo.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^1.MOD1_300^Mensaje 300 del sistema 1 Módulo 1
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^1.PERFIL_001^No se permiten nombres duplicados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^1.PERMISO_001^No se permiten nombres duplicados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^1.PERMISO_002^No fue posible realizar la asignación de permisos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^1.VALIDA_00^Los campos: {0}, son requeridos, proporcione un valor.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.CAT_01^La aplicación [1] ya se encuentra registrada previamente.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.CAT_02^El catálogo [1] ya se encuentra registrado previamente para la aplicación [2].
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.EXC_001^Ocurrió un error al ejecutar la sentencia SQL.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.EXC_002^Ocurrió un error de conexión a la base de datos.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.EXC_003^Existe un error en la sentencia:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.EXC_004^Existe un error en los datos enviados a la sentencia:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.EXC_005^La sentencia enviada genera un error de integridad:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.EXC_006^Existe un error al adquirir un candado en la base de datos:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.GEN_000^Ocurrió el siguiente error en el sistema:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.MAIL_001^Falló la autenticación en servidor de correo.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.MAIL_002^Sin conexión a servidor de correo, guardando correo para envío posterior.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.MAIL_003^Ocurrió una excepción en el envío de correo, favor de revisar el log.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.MAIL_004^Ocurrió un error al escribir en la Base de Datos.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.MAIL_005^No se encontró el archivo para adjuntar al correo.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^2.MOD1_100^Ocurrió un error al procesar el archivo: [NomArchivo]
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.ACTIVA.HEADER^Activar correo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.ACTIVA.MSGCONFIRMA^¿Está seguro de activar el correo?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.BCC^BCC
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.BCC.VALIDFORMAT^El formato del campo BCC no es válido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.BCC.COMMENT^Correo con copia oculta
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.BCC.COMMENT.COMPONENT^Correo con copia oculta. Para agregar más de un correo presione la tecla Enter después de agregar el primer correo.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.CC^CC
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.CC.VALIDFORMAT^El formato del campo CC no es válido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.CC.COMMENT^Correo con copia
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.CC.COMMENT.COMPONENT^Correo con copia. Para agregar más de un correo presione la tecla Enter después de agregar el primer correo.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.HEADER^Información de Correos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.MENSAJE^Mensaje
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.MSJ.REQUIRED^El campo Mensaje es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.NUMERO.REQUIRED^El campo Número es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.SISTEMA^Sistema 
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.SUBJECT^Asunto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.SUBJECT.REQUIRED^El campo Asunto es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.SUBJECT.VALIDFORMAT^El formato del campo Asunto no es válido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.SUBJECT.COMMENT^Asunto con el que va dirigido el correo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.TO^Para
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.TO.REQUIRED^El valor del atributo Para es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.TO.VALIDFORMAT^El formato del campo Para no es válido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.TO.COMMENT^Correo destinatario(s)
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.TO.COMMENT.COMPONENT^Correo destinatario(s). Para agregar más de un correo presione la tecla Enter después de agregar el primer correo.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DESACTIVA.HEADER^Desactivar correo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DESACTIVA.MSGCONFIRMA^¿Está seguro de desactivar el correo?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.FILTRO.HEADER^Mostrar correos de
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.NUMERO^Número
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.REPORTE.NOMBRE^Reporte de Correos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.TEMPLATE.TITULO^Administración de Templates de Correo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.TITULO^Administración de Correos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.UPDATE.HEADER^Nuevo Correo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.ENVIAR.HEADER^Enviar correo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.OPCIONES.ENVIAR^Enviar correo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.EMAIL.VALIDFORMAT^El formato de los correos agregados no es válido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.ADJUNTO^Archivo adjunto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.DATA.ADJUNTAR.ARCHIVO^Adjuntar archivos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.UPLOAD.LIMITSIZE^5728640
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CORREO.UPLOAD.SIZEMESSAGE^Solo se permiten cargar archivos menores o iguales a 5 MB
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ERROR_NO_CATALOGADO^NO está catalogado en el sistema.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ETIQUETA.DATA.CLAVE^Cadena
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ETIQUETA.DATA.CLAVE.REQUIRED^El campo cadena es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ETIQUETA.DATA.VALOR^Valor idioma predeterminado
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ETIQUETA.DATA.VALOR.REQUIRED^El campo valor es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ETIQUETA.NEW.HEADER^Nueva Cadena
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ABAJO^Bajar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ACCESS.ERRORMSG^No tiene permiso de ejecutar esta pantalla
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ACCESS.HEADER^Error de Acceso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ACEPTAR^Aceptar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ACTIVA^Activar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ADD^Agregar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.AMBIENTE.DESARROLLO^DEV
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.AMBIENTE.INTEGRACION^INTEGRA
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.AMBIENTE.QA^QAS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ARRIBA^Subir
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.AUTORIZA^Autorizar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.AYUDA^Ayuda
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.AYUDA.GRAL^General
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.AYUDA.MANUALUSR^Man. Usr.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.BUSCAR^Buscar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CADENAS^Cadenas del Sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CADENAS.CLAVE^Clave
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CADENAS.IDIOMA^Idioma
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CADENAS.MESSAGES^Mensajes Registrados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CADENAS.STRINGS^Cadenas Registradas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CADENAS.VALOR^Valor
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CADENAS.VALORESPARA^Valores para
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CANCELAR^Cancelar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CHOOSELANG^Seleccione su idioma
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CONFIRMA.HEADER^Por favor confirme
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CONFIRMA.MSGCONFIRMA^¿Está seguro de realizar la acción indicada?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.ALL^Todos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.ACTIVO^Activo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.ESTATUS^Estatus
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.FALSE^No
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.INACTIVO^Inactivo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DATA.TRUE^Sí
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DETALLE^Detalle
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.EDITAR^Editar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ELIMINAR^Eliminar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.EMPTYMESSAGE^No se encontraron registros con el filtro indicado
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ERROR.HANDLER.CLASS^Clase
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ERROR.HANDLER.CODE^Código de Error
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ERROR.HANDLER.DESC^Descripción
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ERROR.HANDLER.STACK^StackTrace
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ERROR.HANDLER.TITLE^Manejo de Errores - Error Detectado
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ERROR.HANDLER.TYPE^Tipo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ERROR.HANDLER.URI^URL Solicitado
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.EXCEL^XLS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.EXIT^Cerrar Sesión
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.EXPLORER.ERRORMSG^Esta aplicación requiere el uso de Mozilla FireFox, imposible continuar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.EXPORT.ALL^Exportar todo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.EXPORT.PAGE^Exportar página
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.EXPORT.PRINT^Imprimir
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.EXPORTAR^Exportar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.FILELOADER.ERROR^Error en Línea: %s | Atributo: %s | PosIni: %s | PosFin: %s | Error: %s
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.FILTER.WAIT.MESSAGE^Por favor espera, tu solicitud está siendo procesada.....
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.GUARDAR^Guardar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ID^Identificador
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.IMAGE.SAVE^Oprima botón derecho y seleccione ''Guardar imagen''
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.IMAGEN^Imagen
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.IMPRIMIR^Imprimir
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.INACTIVA^Desactivar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.LIBERAR^Liberar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MENSAJES.TITULO^Mensajes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MESSAGES^Mensajes Sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MOSTRAR^Mostrar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MOSTRAR.IRPAGINA^Ir a Página:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MOSTRAR.PAGINA^Página
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MOSTRAR.PAGINA.ROWS^1,2,3,4,5,10,15,20,25,50,75,100
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MOSTRAR.PAGINA.X.DE.Y^de
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MOSTRAR_REGS_PREFIJO^Mostrar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MOSTRAR_REGS_SUFIJO^registros.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MOUSE.RIGHTBUTTON.MSG^No puede emplearse el botón derecho del mouse
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.NOMBREMES^Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.NOMBREMESABREV^ENE,FEB,MAR,ABR,MAY,JUN,JUL,AGO,SEP,OCT,NOV,DIC
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.NUEVO^Nuevo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.OPTS.ALL^Todos...
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.PAGINATOR.CURRROWTEMPLATE^Página: ({currentPage} de {totalPages})     Registros: ({totalRecords})
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.PAGINATOR.TEMPLATE^{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {CurrentPageReport} Mostrar {RowsPerPageDropdown} registros.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.PAGINATOR.TEMPLATE.NONUMROWS^{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {CurrentPageReport}
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.PDF^PDF
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.REPORT.UM^Reporte User Management
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.REPORTE.AUTOR^Software Factory
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.RESIZE^Ajustar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.RESIZE.MESSAGE^Ejecute su consulta para actualizar la vista
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SAVE.EXITO^Se ha guardado satisfactoriamente.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SEARCH.ALLFIELDS^Buscar en todo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SEARCH.ALLFIELDS.KEY^Proporcione un valor...
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SELECCIONAR^Seleccionar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SESSION.MESSAGE.CONTINUE^¿Deseas continuar tu sesión?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SESSION.MESSAGE.POST^segundos.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SESSION.MESSAGE.PRE^Serás redirigido fuera del sistema en
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SESSION.TITLE^¡Tu sesión está por expirar!
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.SWF^Software Factory
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.AVANCE^Avance
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.CANCEL^Cancelar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.CHOOSE^Seleccione...
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.FASE^Fase
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.FASE.X.DE.Y^de
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.FILES^1
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.HEADER^Cargar archivo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.LIMITMESSAGE^Solo se permite subir 1 archivo a la vez
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.LIMITSIZE^10240000
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.SIZEMESSAGE^Solo se permiten archivos menores o iguales a 1000kb
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.STATUS.TITLE^Avance del proceso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.TYPEMESSAGE^Solo se permiten archivos de tipo gif, jpg, png, txt, csv, xls, zip, rar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.TYPES^gif|jpe?g|png|txt|csv|xls|zip|rar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.UPLOAD^Cargar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPLOAD.NOFILESELECT^No se ha seleccionado un archivo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DOWNLOAD.LAYOUT^Layout
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.VERSION.LABEL^Versión
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.VERSION.NUM^1.0.0
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.VISTAPRELIMINAR^Vista preliminar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ZOOM^Ampliar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.TOTAL^Total
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.REVIEW^Mostrar detalle
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.ACTIVA.HEADER^Por favor confirme
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.ACTIVA.MSGCONFIRMA^¿Está seguro de activar el idioma?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.CODIDIOMA^Código de Idioma
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.CODIDIOMA.REQUIRED^El Código de idioma es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.CODIDIOMA.VALIDFORMAT^El Código de idioma solo acepta dos letras minúsculas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.CODPAIS^Código de país
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.CODPAIS.REQUIRED^El Código de país es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.CODPAIS.VALIDFORMAT^El Código de país solo acepta dos letras mayúsculas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.HEADER^Administración de Idiomas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.FORMATOFECHA^Formato
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.IDIOMA^Idioma
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.IDIOMA.REQUIRED^El atributo idioma es requerido, favor de proporcionar el valor
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.IDIOMA.VALIDFORMAT^El atributo idioma no tiene el formato correcto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DATA.PREDETERMINADO^Idioma Predeterminado
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DESACTIVA.HEADER^Por favor confirme
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.DESACTIVA.MSGCONFIRMA^¿Esta seguro de desactivar el idioma?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.REPORTE.NOMBRE^Idiomas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.TITULO^Administración de Idiomas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^IDIOMA.UPDATE.HEADER^Actualización de Idioma

(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.ACTIVA.HEADER^Activar 
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.ACTIVA.MSGCONFIRMA^¿Está seguro de Activar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.DATA.HEADER^Exportar Datos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.DATA.LABEL.REQUIRED^El campo Etiqueta es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.DATA.PERMISO.REQUIRED^El campo Permiso es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.DELETE.HEADER^Eliminar opción definitivamente
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.DELETE.MSGCONFIRMA^¿Está seguro de eliminar permanentemente la opción seleccionada?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.DESACTIVA.HEADER^Desactivar 
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.DESACTIVA.MSGCONFIRMA^¿Está seguro de Desactivar?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.EDIT^Editar Opciones de Menú
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.ENABLED^Habilitado
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.ICON^Icon Url
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.IDPERMISO^Permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.LABEL^Etiqueta
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.LABEL.PERMISO^Permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.LABEL.VALOR^Valor de la Etiqueta
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.ORDERHINT^Orderhint
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.PARENT^Parent_ID
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.REPORTE.NOMBRE^Reporte de Menú
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.TITULO^Administración de Opciones de Menú
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENUCONFIG.URL^Url
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.ACTIVA.HEADER^Activar parámetro
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.ACTIVA.MSGCONFIRMA^¿Está seguro de activar el parámetro?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.CLAVE^Clave
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.DATA.CAT^Catálogo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.DATA.GRUPO^Grupo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.DATA.HEADER^Parámetros de Configuración
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.DATA.PARAMETRO^Valor
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.DATA.PARAMETRO.REQUIRED^El campo Clave es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.DATA.PARAMETRO.VALIDFORMAT^El formato del campo Parametro no es valido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.DATA.SISTEMA^Sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.DATA.VALOR^Valor
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.DESACTIVA.HEADER^Desactivar parámetro
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.DESACTIVA.MSGCONFIRMA^¿Está seguro de desactivar el parámetro?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.DESCRIPCION^Descripción
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.FILTRO.HEADER^Filtrar información empleando
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.REPORTE.NOMBRE^Reporte de Parámetros
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.TITULO^Administración de Parámetros
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PARAMETRO.UPDATE.HEADER^Nuevo Valor
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.ACTIVA.HEADER^Activa perfil
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.ACTIVA.MSGCONFIRMA^¿Está seguro de activar el perfil?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.ADD.PERMISO^Agregar permisos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.DATA.HEADER^Perfiles registrados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.DATA.PERFIL^Perfil
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.DATA.DESCRIPCION^Descripción
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.DATA.PERFIL.REQUIRED^El campo Perfil es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.DATA.PERFIL.VALIDFORMAT^El formato del campo Perfil no es valido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.DESACTIVA.HEADER^Desactivar perfil
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.DESACTIVA.MSGCONFIRMA^¿Está seguro de desactivar el perfil?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.REPORTE.NOMBRE^Reporte de Perfiles
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.TITULO^Administración de Perfiles
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERFIL.UPDATE.HEADER^Agregar o Modificar Pefil
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.ACTIVA.HEADER^Activar permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.ACTIVA.MENU.HEADER^Mostrar en Config. Menú
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.ACTIVA.MENU.MSGCONFIRMA^¿Está seguro de mostrar el permiso en el menú?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.ACTIVA.MSGCONFIRMA^¿Está seguro de activar el permiso?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.ASIGNAR.HEADER^Asignar permisos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.DATA.HEADER^Permisos registrados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.DATA.MOSTRARENMENU^Mostrar en Menú
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.DATA.PERMISO^Permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.DATA.DESCRIPCION^Descripción
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.DATA.PERMISO.REQUIRED^El campo Permiso es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.DATA.PERMISO.VALIDFORMAT^El formato del campo Permiso no es valido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.DATA.QUITARENMENU^Quitar de Menú
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.DESACTIVA.HEADER^Desactivar permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.DESACTIVA.MENU.HEADER^Quitar de menú
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.DESACTIVA.MENU.MSGCONFIRMA^¿Está seguro de quitar el permiso del menú?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.DESACTIVA.MSGCONFIRMA^¿Está seguro de desactivar el permiso?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.FILTRO.HEADER^Filtrar permisos empleando
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.FILTRO.PERFIL^Perfil
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.REPORTE.NOMBRE^Reporte de Permisos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.TITULO^Administración de Permisos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.NEW.HEADER^Agregar Permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PERMISO.UPDATE.HEADER^Modificar Permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.BEANNAME^Nombre Bean
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.BEANPACKAGE^Paquete Bean
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.BEANPATH^Ruta Bean
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.ENTITYNAME^Nombre entidad
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.ENTITYPACKAGE^Ruta entidad
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.HEAD^Crear Catálogo Simple
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.JSFNAME^Nombre JSF
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.JSFPATH^Ruta XHTML
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.NAME^Nombre catálogo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.PATH^Ruta Workspace
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.PROJNAME^Nombre proyecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.PROJPATH^Ruta Proyecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.SERVICENAME^Nombre servicio
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^WIZARD.SIMPLE_CATALOG.SERVICEPACKAGE^Ruta servicio
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ACTIVA.HEADER^Activar Registro
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ACTIVA.MSGCONFIRMA^¿Está seguro de activar el registro?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DESACTIVA.HEADER^Desactivar Registro
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DESACTIVA.MSGCONFIRMA^¿Está seguro de desactivar el registro?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.RELOAD^Actualizar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CARGAMASIVA.VALIDAR^Validar Información
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CARGAMASIVA.ARCHIVO.VALIDO^El archivo %s es válido. Oprima el botón Guardar para registrar la información.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CARGAMASIVA.ARCHIVO.ERRORCARGA^No se pudo recuperar el archivo cargado.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CARGAMASIVA.SHEET.NOTFOUND^No se encontró la hoja de nombre %s. Compare su archivo con el layout.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.COPIAR^Copiar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.PEGAR^Pegar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CARGAMASIVA.SHEET.NOTFOUND^No se encontró la hoja de nombre %s. Compare su archivo con el layout.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CARGAMASIVA.ARCHIVO.ERRORCARGA^No se pudo recuperar el archivo cargado.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CARGAMASIVA.ARCHIVO.VALIDO^El archivo %s es válido. Oprima el botón Guardar para registrar la información.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CARGAMASIVA.VALIDAR^Validar Información

(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^AUDITORIAREPORTES.TITULO^Consulta y depuración de auditoría de ejecución de reportes y consultas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^AUDITORIAREPORTES.DATA.HEADER^Ejecución de reportes y consultas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^AUDITORIAREPORTES.REPORTE.NOMBRE^AuditoriaReportes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^AUDITORIAREPORTES.UPDATE.HEADER^Detalle de ejecución de reportes y consultas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^AUDITORIAREPORTES.DATA.ID^Identificador
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^AUDITORIAREPORTES.DATA.ID.USR^Usuario
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^AUDITORIAREPORTES.DATA.ID.PANTALLA^Pantalla
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^AUDITORIAREPORTES.DATA.ID.REPORTE^Reporte
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^AUDITORIAREPORTES.DATA.FECHA.EJECUCION^Fecha Ejecución
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^AUDITORIAREPORTES.DATA.FILTROS.APLICADOS^Filtros Aplicados

(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.TITULO^Consulta y depuración de registro de trazabilidad de información
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.UPDATE.HEADER^Trazabilidad de información
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.DATA.HEADER^Información de trazabilidad de información
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.REPORTE.NOMBRE^Trazabilidad información
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.APP.LOG.ID^Id traza
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.APP.LOG.ACCION^Acción
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.APP.LOG.FECHA^Fecha
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.APP.LOG.MENSAJE^Mensaje
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.APP.LOG.REF.ID^Id Entidad
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.APP.LOG.PARENT.REF.ID^Id Padre
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.APP.LOG.USUARIO^Usuario
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.APP.LOG.ENTIDAD^Entidad
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.APP.LOG.REV.ID^Revisión
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^TRAZABLIDAD.APP.LOG.REV.TYPE^Tipo Revisión

#--Insert de Fwk_Cadena_Idioma para la tabla: FWK_CATALOGO_PANTALLAS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.ID^Identificador
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.ID.COMMENT^Identificador de la pantalla dentro del sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.ID.VALIDFORMAT^El campo Identificador tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.ID.REQUIRED^El campo Identificador es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.NOMBREAMOSTRAR^Nombre a Mostrar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.NOMBREAMOSTRAR.COMMENT^Nombre de la pantalla que se mostrará al usuario para realizar la configuración de reportes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.NOMBREAMOSTRAR.VALIDFORMAT^El campo Nombre a Mostrar tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.NOMBREAMOSTRAR.REQUIRED^El campo Nombre a Mostrar es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.RUTAPANTALLA^Ruta de Pantalla
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.RUTAPANTALLA.COMMENT^Ruta interna de la pantalla dentro del sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.RUTAPANTALLA.VALIDFORMAT^El campo Ruta de Pantalla tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.RUTAPANTALLA.REQUIRED^El campo Ruta de Pantalla es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.NOMBREPANTALLA^Nombre de Pantalla
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.NOMBREPANTALLA.COMMENT^Nombre de la pantalla dentro del sitema, en conjunto con la ruta permite determinar los permisos asignados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.NOMBREPANTALLA.VALIDFORMAT^El campo Nombre de Pantalla tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.NOMBREPANTALLA.REQUIRED^El campo Nombre de Pantalla es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.ESTATUS^Activo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.ESTATUS.COMMENT^Estado que guarda el registro dentro de la base de datos, 1=Activo, 0=Inactivo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.ESTATUS.VALIDFORMAT^El campo Estatus tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.ESTATUS.REQUIRED^El campo Estatus es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.FECHACREACION^Fecha Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.FECHACREACION.COMMENT^Contiene la fecha y hora de creación del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.FECHACREACION.VALIDFORMAT^El campo Fecha Creación tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.FECHACREACION.REQUIRED^El campo Fecha Creación es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.USRCREACION^Usuario Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.USRCREACION.COMMENT^Contiene el id de usuario de creación del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.USRCREACION.VALIDFORMAT^El campo Usuario Creación tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.USRCREACION.REQUIRED^El campo Usuario Creación es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.FECHAACTUALIZACION^Fecha Actualización
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.FECHAACTUALIZACION.COMMENT^Contiene la fecha y hora de actualización del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.FECHAACTUALIZACION.VALIDFORMAT^El campo Fecha Actualización tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.FECHAACTUALIZACION.REQUIRED^El campo Fecha Actualización es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.USRACTUALIZA^Usuario Actualiza
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.USRACTUALIZA.COMMENT^Contiene el id de usuario de actualización del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.USRACTUALIZA.VALIDFORMAT^El campo Usuario Actualiza tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.USRACTUALIZA.REQUIRED^El campo Usuario Actualiza es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.DISPONIBLES^Pantallas disponibles
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.DISPONIBLES.COMMENT^Pantallas disponibles en la aplicación


#--Insert de Fwk_Cadena_Idioma para el catálogo: FWK_CATALOGO_PANTALLAS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.DATA.HEADER^Datos Registrados de Pantallas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.NEW.HEADER^Nueva Pantalla
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.UPDATE.HEADER^Actualización de Pantalla
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.TITULO^Catálogo de Pantallas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOPANTALLAS.REPORTE.NOMBRE^Catálogo de Pantallas

#--Insert de Fwk_Cadena_Idioma para la tabla: FWK_CATALOGO_REPORTES
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.ID^Identificador
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.ID.COMMENT^Identificador del reporte dentro del sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.ID.VALIDFORMAT^El valor del atributo Identificador tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.ID.REQUIRED^El valor del atributo Identificador es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.NOMBREAMOSTRAR^Nombre a Mostrar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.NOMBREAMOSTRAR.COMMENT^Nombre del reporte que se mostrará en las pantallas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.NOMBREAMOSTRAR.VALIDFORMAT^El campo Nombre a Mostrar tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.NOMBREAMOSTRAR.REQUIRED^El campo Nombre a Mostrar es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.RUTAREPORTE^Ruta de Reporte
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.RUTAREPORTE.COMMENT^Ruta interna del reporte, se emplea para la ejecución de reportes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.RUTAREPORTE.VALIDFORMAT^El campo Ruta de Reporte tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.RUTAREPORTE.REQUIRED^El valor del atributo Ruta de Reporte es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.PROCESO^Proceso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.PROCESO.COMMENT^Proceso al que se asociará el reporte
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.NOMBREREPORTE^Nombre de Reporte
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.NOMBREREPORTE.COMMENT^Nombre interno del reporte, es el nombre que será empleado para la ejecución
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.NOMBREREPORTE.VALIDFORMAT^El campo Nombre tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.NOMBREREPORTE.REQUIRED^El valor del atributo Nombre de Reporte es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.ESTATUS^Estatus
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.ESTATUS.COMMENT^Estado que guarda el registro dentro de la base de datos, 1=Activo, 0=Inactivo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.ESTATUS.VALIDFORMAT^El valor del atributo Estatus tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.ESTATUS.REQUIRED^El valor del atributo Estatus es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.FECHACREACION^Fecha Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.FECHACREACION.COMMENT^Contiene la fecha y hora de creación del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.FECHACREACION.VALIDFORMAT^El valor del atributo Fecha Creación tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.FECHACREACION.REQUIRED^El valor del atributo Fecha Creación es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.USRCREACION^Usuario Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.USRCREACION.COMMENT^Contiene el id de usuario de creación del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.USRCREACION.VALIDFORMAT^El valor del atributo Usuario Creación tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.USRCREACION.REQUIRED^El valor del atributo Usuario Creación es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.FECHAACTUALIZACION^Fecha Actualización
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.FECHAACTUALIZACION.COMMENT^Contiene la fecha y hora de actualización del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.FECHAACTUALIZACION.VALIDFORMAT^El valor del atributo Fecha Actualización tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.FECHAACTUALIZACION.REQUIRED^El valor del atributo Fecha Actualización es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.USRACTUALIZA^Usuario Actualiza
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.USRACTUALIZA.COMMENT^Contiene el id de usuario de actualización del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.USRACTUALIZA.VALIDFORMAT^El valor del atributo Usuario Actualiza tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.USRACTUALIZA.REQUIRED^El valor del atributo Usuario Actualiza es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.CALENDARIZABLE^Calendarizable
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.CALENDARIZABLE.COMMENT^Identificador de reportes que serán calendarizados, 1=Activo, 0=Inactivo

#--Insert de Fwk_Cadena_Idioma para el catálogo: FWK_CATALOGO_REPORTES
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.DATA.HEADER^Datos Registrados de Reportes por Pantalla
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.NEW.HEADER^Nuevo Reporte
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.UPDATE.HEADER^Actualización de Reporte
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.TITULO^Catálogo de Reportes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOREPORTES.REPORTE.NOMBRE^Catálogo de Reportes

#--Insert de Fwk_Cadena_Idioma para la tabla: FWK_CATALOGO_TIPO_EXPORTACION
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ID^Identificador
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ID.COMMENT^Identificador del tipo de exportación en el sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ID.VALIDFORMAT^El valor del atributo Identificador tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ID.REQUIRED^El valor del atributo Identificador es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.NOMBRETIPOEXPORTACION^Nombre de Tipo Exportación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.NOMBRETIPOEXPORTACION.COMMENT^Nombre del tipo de exportación que será mostrado al usuario durante la configuración de permisos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.NOMBRETIPOEXPORTACION.VALIDFORMAT^El valor del atributo Nombre de Tipo Exportación tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.NOMBRETIPOEXPORTACION.REQUIRED^El valor del atributo Nombre de Tipo Exportación es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ABREVIATURATIPOEXPORTACION^Abreviatura de Tipo Exportación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ABREVIATURATIPOEXPORTACION.COMMENT^Abreviatura que será mostrada para el tipo de exportación, es la extensión que será mostrada al usuario
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ABREVIATURATIPOEXPORTACION.VALIDFORMAT^El valor del atributo Abreviatura de Tipo Exportación tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ABREVIATURATIPOEXPORTACION.REQUIRED^El valor del atributo Abreviatura de Tipo Exportación es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ESTATUS^Estatus
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ESTATUS.COMMENT^Estado que guarda el registro dentro de la base de datos, 1=Activo, 0=Inactivo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ESTATUS.VALIDFORMAT^El valor del atributo Estatus tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.ESTATUS.REQUIRED^El valor del atributo Estatus es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.FECHACREACION^Fecha Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.FECHACREACION.COMMENT^Contiene la fecha y hora de creación del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.FECHACREACION.VALIDFORMAT^El valor del atributo Fecha Creación tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.FECHACREACION.REQUIRED^El valor del atributo Fecha Creación es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.USRCREACION^Usuario Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.USRCREACION.COMMENT^Contiene el id de usuario de creación del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.USRCREACION.VALIDFORMAT^El valor del atributo Usuario Creación tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.USRCREACION.REQUIRED^El valor del atributo Usuario Creación es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.FECHAACTUALIZACION^Fecha Actualización
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.FECHAACTUALIZACION.COMMENT^Contiene la fecha y hora de actualización del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.FECHAACTUALIZACION.VALIDFORMAT^El valor del atributo Fecha Actualización tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.FECHAACTUALIZACION.REQUIRED^El valor del atributo Fecha Actualización es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.USRACTUALIZA^Usuario Actualiza
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.USRACTUALIZA.COMMENT^Contiene el id de usuario de actualización del registro.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.USRACTUALIZA.VALIDFORMAT^El valor del atributo Usuario Actualiza tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.USRACTUALIZA.REQUIRED^El valor del atributo Usuario Actualiza es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.SOLOPARAREPORTES^Solo para reportes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.SOLOPARAREPORTES.COMMENT^Indica si el tipo de exportación solo está disponible para reportes, en caso contrario se emplea para reportes y exportación de tablas de datos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.SOLOPARAREPORTES.VALIDFORMAT^El valor del atributo Solo para reportes tiene un formato incorrecto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.SOLOPARAREPORTES.REQUIRED^El valor del atributo Solo para reportes es requerido


#--Insert de Fwk_Cadena_Idioma para el catálogo: FWK_CATALOGO_TIPO_EXPORTACION
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.DATA.HEADER^Datos Registrados de Tipo de Exportación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.NEW.HEADER^Nuevo Tipo de Exportación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.UPDATE.HEADER^Actualización de Tipo de Exportación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.TITULO^Catálogo de Tipo de Exportación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CATALOGOTIPOEXPORTACION.REPORTE.NOMBRE^Catálogo de Tipo de Exportación

#--Insert de Fwk_Cadena_Idioma para el catálogo: Asignar reportes por pantalla
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ASIGNAREPORTEPANTALLA.TITULO^Asignación de Reportes por Pantalla
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ASIGNAREPORTEPANTALLA.FILTRO.HEADER^Filtro
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ASIGNAREPORTEPANTALLA.FILTRO.PANTALLA^Pantalla


(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.LIMPIAR^Limpiar campos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DESCARGAR^Descargar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.LOGIN^Iniciar sesión
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.LOGIN.MENSAJE^Seleccione un usuario para iniciar sesión
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.LOGIN.USUARIO^Usuario:
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.LOGIN.USUARIO.REQUIRED^El atributo Usuario es requerido.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.LOGIN.USUARIO.COMMENT^Usuario activo con el que se iniciará la sesión dentro de SICAM.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.LOGIN.BLOQUEADO.MENSAJE^La pantalla de inicio de sesión no está disponible.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.LOGIN.BLOQUEADO.DETALLE^Revise su configuración para habilitar esta función.

(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DELETE.EXITO^Se ha borrado satisfactoriamente.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.UPDATE.EXITO^Se ha actualizado satisfactoriamente.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.CANCEL.EXITO^Se ha cancelado satisfactoriamente.

(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ATTACHMENT.HEADER^Archivo adjunto
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ATTACHMENT.VIEW.HEADER^Visualizar documento
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ATTACHMENT.ARCHIVO^Nombre del archivo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^ATTACHMENT.FORMATOARCHIVO^Formato

(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MENUTYPE^Tipo de Menú
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MENUTYPE.STACK^Apilado
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MENUTYPE.CHAIN^Vertical
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.MENUTYPE.MEGA^Horizontal


#--Insert de Fwk_Cadena_Idioma para: CONSULTAS DINAMICAS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CONSULTASDINAMICAS.DATA.HEADER^Reportes de Consultas Dinámicas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CONSULTASDINAMICAS.UPDATE.HEADER^Consultas Dinámicas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CONSULTASDINAMICAS.TITULO^Consultas Dinámicas


#--Insert de FWK_CADENA_IDIOMA para la tabla: PROD_CLAVE_ENSAMBLE
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PANTALLA.CONSULTAS.DINAMICAS.DATA.TITULO^Catálogo de Consultas Dinámicas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PANTALLA.CONSULTAS.DINAMICAS.DATA.HEADER.TITULO^Reportes Dinámicos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PANTALLA.CONSULTAS.DINAMICAS.DATA.HEADER.NUEVO^Nuevo Reporte
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PANTALLA.CONSULTAS.DINAMICAS.DATA.HEADER.ACTUALIZAR^Actualizar Reporte

(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PANTALLA.CONSULTAS.DINAMICAS.DATA.TITULO.NOMBRE^Nombre
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PANTALLA.CONSULTAS.DINAMICAS.DATA.TITULO.VISTA^Vista
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PANTALLA.CONSULTAS.DINAMICAS.DATA.TITULO.DESCRIPCION^Descripción
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PANTALLA.CONSULTAS.DINAMICAS.DATA.TITULO.CONGELADOS^Congelados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PANTALLA.CONSULTAS.DINAMICAS.DATA.TITULO.CAMPOS^Campos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PANTALLA.CONSULTAS.DINAMICAS.DATA.TITULO.FECHACREACION^Fecha Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^PANTALLA.CONSULTAS.DINAMICAS.DATA.TITULO.FECHAACTUALIZACION^Fecha Actualización

#--Insert de FwkCadenaIdioma para la gestión de timers
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.TITULO^Gestión de Timers
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.MSGCONFIRMA^¿Está seguro de ejecutar manualmente el timer seleccionado?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.MSGCONFIRMA.HEADER^Ejecución de Timers
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.DATA.HEADER^Timers registrados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.DATA.KEYVALUE^Nombre
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.DATA.DESCRIPCION^Descripción
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.DATA.USRACTUALIZA^Usuario Ejecutó
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.DATA.FECHAACTUALIZA^Fecha Ejecución
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.EJECUTAR^Ejecutar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.EJECUTADO^Timer enviado a ejecutar correctamente
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.NOTFOUND^Timer no encontrado, imposible ejecutar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONTIMERS.GO_PROCESO^La ejecución del timer ha comenzado correctamente.

#--Insert de FwkCadenaIdioma para la gestión de recursos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^RESOURCES.TITULO^Gestión de Recursos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^RESOURCES.MSGCONFIRMA^¿Está seguro de reiniciar manualmente el recurso seleccionado?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^RESOURCES.MSGCONFIRMA.HEADER^Reinicio de Recursos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^RESOURCES.DATA.HEADER^Recursos registrados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^RESOURCES.DATA.NAME^Nombre
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^RESOURCES.RESET^Reiniciar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^RESOURCES.RESETED^Recurso enviado a reiniciar correctamente
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^RESOURCES.NOTFOUND^Recurso no encontrado, imposible reiniciar

#--Se insertan etiquetas parra la pantalla Asociar Tipo de Archivos a un Proceso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PROCESO^Asignación tipos de Archivos a Procesos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PROCESO.FILTRARPROCESO^Filtro
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PROCESO.NOMBREPROCESO^Proceso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PROCESO.TIPOARCHIVO^Datos registrados de Tipo de Documento
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PROCESO.ARCHIVOIDENTIFICADOR^Identificador
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PROCESO.ARCHIVONOMBRE^Tipo de documento
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PROCESO.ARCHIVOEXTENSION^Extensión
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PROCESO.ARCHIVOESTATUS^Estatus

#--Se insertan etiquetas parra la pantalla Asociar Usuarios del Sistema a un Perfil de la aplicación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PERMISO.PERFIL^Asignación de Usuarios a un Perfil de la Aplicación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PERMISO.PERFIL.FILTROPERFIL^Filtrar Perfiles
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PERMISO.PERFIL.NOMBREPERFIL^Nombre del Perfil
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PERMISO.PERFIL.TABLAUSUARIOS^Usuarios Registrados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PERMISO.PERFIL.IDENTIFICADOR^Identificador
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PERMISO.PERFIL.IDENTIFICADORSISTEMA^Identificador del Sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PERMISO.PERFIL.NOMBRE^Nombre Completo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PERMISO.PERFIL.EMAIL^Correo Electrónico
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PERMISO.PERFIL.ESTATUS^Estatus
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.PERMISO.PERFIL.REPORTNAME^Asignación de Usuarios a un Perfil de la Aplicacion

#--Se insertan etiquetas parra la pantalla Delegación de Permisos a usuarios del sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.DELEGACIONPERMISO^Catálogo de Seguridad para la delegación de Permisos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.DELEGACIONPERMISO.PERMISOREGISTRADO^Usuarios con permisos registrados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.DELEGACIONPERMISO.PERMISOREGISTRADO^Usuarios con permisos registrados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.DELEGACIONPERMISO.PERMISODENEGADO^Revocar Permiso al Usuario
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.DELEGACIONPERMISO.DELEGACIONPERMISO^Delegación de un Permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.DELEGACIONPERMISO.DELEGACIONPERMISOCHECKBOX^Usuario específico del sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.DELEGACIONPERMISO.TOOLTIP.DELEGACIONPERMISOCHECKBOX^Marque el checkbox si desea seleccionar a cualquier Usuario del Sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.ERROR.USURIO_RECIBE^Se necesita Seleccinar un Usuario para Delegar el Permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL_ERROR_PERFIL_RECIBE^Se necesita Seleccinar un Perfil para Delegar el Permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL_ERROR_USR_OTORGA_PERMISO^Debe seleccionar al Usuario que Otorga el Permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.DELEGACIONPERMISO.DELEGACIONPERMISOLATERAL^Delegar Permiso a Usuarios con el mismo Rol
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.DELEGACIONPERMISO.DELEGACIONPERMISOLATERAL.UPDATE^Actualización Permiso Delegado a Usuario con el mismo Rol
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^DELEGACIONPERMISOS.DATA.FECHAINICIAL.START_DATE_BEFORE_END_DATE^El valor de la Fecha Final tiene que ser mayor a la Fecha Inicial
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DATA.DELEGACIONPERMISO.DELEGACIONPERMISOUSERS^Delegar Permiso a Cualquier Usuario del Sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DELEGACIONPERMISO.REVOCAR_PERMISO^Revocar permiso
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^HEADER.DELEGACIONPERMISO.REVOCAR_PERMISO_DESACTIVA.MSGCONFIRMA^¿Está seguro de revocar el permiso?
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DELEGACIONPERMISO.REPORTE.NAME^Usuarios con Permisos Registrados
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.DELEGACIONPERMISO.DATAFILE.NAME^Catálogo de Seguridad Usuarios con Permisos Registrados

#--Insert de Fwk_Cadena_Idioma para el catálogo: SEG_USUARIO
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.TITULO^Administración de usuarios
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.HEADER^Datos Registrados de Usuarios
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.NEW.HEADER^Nuevo Usuario
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.UPDATE.HEADER^Actualización de Usuario
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.REPORTE.NOMBRE^Catálogo de Acciones
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.ID^Id
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.ID.COMMENT^Id numérico del usuario
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.USERID^Usuario Id
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.USERID.COMMENT^UserId corresponde al identificador numérico del usuario
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.NOMBRE^Nombre
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.APATERNO^Apellido Paterno
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.AMATERNO^Apellido Materno
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.CORREOE^Correo Electrónico
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.REQUIRED^El valor del campo es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.ID.COMMENT^Id numerico del usuario
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.ID.UNIQUE^El usuario ya existe
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.CORREOELECTRONICO.VALIDFORMAT^Correo invalido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.PERFIL.UNIQUE^El usuario ya existe
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.REPORTE.NOMBRE^Gestión Usuarios
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.ID.REQUIRED^El valor del campo Id es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.USERID.REQUIRED^El valor del campo Id Usuario es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.NOMBRE.REQUIRED^El valor del campo Nombre es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.APATERNO.REQUIRED^El valor del campo Apellido Paterno es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.AMATERNO.REQUIRED^El valor del campo Apellido Materno es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.CORREOE.REQUIRED^El valor del campo Correo Electrónico es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^LOGIN.HEADER^Login
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^LOGIN.USER^Usuario
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^LOGIN.USER.REQUIRED^Usuario requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^LOGIN.INGRESAR^Ingresar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.NUMERO_CONTROL^No. Control
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.NUMERO_CONTROL.REQUIRED^El Número de Control es requerido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.USRCREACION^Usuario Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.FECHACREACION^Fecha Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.USRACTUALIZA^Usuario Actualiza
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.FECHAACTUALIZACION^Fecha Actualización
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.APELLIDO^Apellido
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GESTIONUSUARIO.DATA.APELLIDO.REQUIRED^El valor del campo Apellido es requerido

(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^GENERAL.JASPER^.jasper

(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.ID^Identificador
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.ID.REPORTE^Reporte
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.FECHA.DEBE.EJECUTAR^Fecha por Ejecutar
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.FECHA.EJECUCION^Fecha Ejecución
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.ESTATUS^Estatus
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.FECHA.CREACION^Fecha Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.USR.CREACION^Usuario Creación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.FECHA.ACTUALIZACION^Fecha Actualización
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.USR.ACTUALIZA^Usuario Actualiza
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.DATA.HEADER^Calendarizar ejecución de reportes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.UPDATE.HEADER^Realizar calendarización
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.ANIO^Año
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.MES^Mes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.MES.ANTERIOR^Mes Anterior
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.MES.SIGUIENTE^Mes Siguiente
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.ANIO.ANTERIOR^Año Anterior
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.ANIO.SIGUIENTE^Año Siguiente
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.HOY^Hoy
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.PERIODICIDAD^Periodicidad
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.OPCIONES^Opción de ejecución programada 
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.HASTA.LA.FECHA^Hasta la fecha
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.HASTA.LA.FECHA.VALIDFORMAT^Debe colocar una fecha valida
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.REPETICIONES^Repeticiones 
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.CANCELAR^Cancelar todas las ejecuciones
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.CANCELA.HEADER^Cancelar ejecución 
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.CANCELAR.TODO^Esto cancelara las ejecuciones desde la fecha actual hasta la fecha seleccionada. Si es una fecha anterior a la actual solo cancela esta.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.CANCELAR.UNO^Solo cancela la ejecución seleccionada.
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^CALENDARIO.REPORTE.CANCELA.NOTA^Nota: Solo es posible cancelar la ejecución de procesos futuros
