ID_IDIOMA^CLAVE^VALOR
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Administracion^Administración
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.CATALOGOS^Catálogos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.ConfiguracionAMS^Configuración para AMS
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Estadistica^Estadísticas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Idioma^Idiomas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Inicio^Inicio
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Menu^Menú de opciones
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Parametro^Parámetros
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Perfil^Perfiles
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Permiso^Permisos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Principal^Frecuente
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Proceso^Procesos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Reporte^Reportes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Salir^Salir
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Seguridad^Seguridad
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.Template^Template de correos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.AUTORIZACIONES^Autorizaciones
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.APROBACIONCONFIGURAFLUJO^Aprobación Configura Flujo
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.NOTIFICACIONES.BANDEJA^Bandeja de asuntos pendientes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.APROBACIONES^Aprobaciones
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.APROBACIONREASIGNARTAREAS^Aprobacion de tareas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.GESTIONRESOURCES^Gestión de Recursos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.GESTIONTIMERS^Gestión de Timers
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.GESTIONUSUARIOS^Administración de Usuarios
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.DELEGACIONPERMISOS^Delegación de Permisos
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.SEGUIMIENTOPERFILUSUARIO^Seguimiento Perfil Usuario
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.NOTIFICACIONES^Notificaciones
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.NOTIFICACIONES.ADMINISTRACION^Gestión de notificaciones
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.NOTIFICACIONES.ADMINISTRACION.ENVIARNOTIFICACIONESPORPERFIL^Enviar Notificaciones a Grupos de Usuarios Concesionarios
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.NOTIFICACIONES.ADMINISTRACION.ENVIARNOTIFICACIONESUSUARIOSSISTEMA^Enviar Notificaciones a Grupos de Usuarios Del Sistema
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.AUDITORIA^Auditoría
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.AUDITORIASERVICIOSWEB^Ejecución de servicios Web
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.AUDITORIAREPORTES^Ejecución de reportes y consultas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.AUDITORIATRAZABILIDAD^Trazabilidad de información
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.CONFIGURAREPORTES^Reportes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.CATALOGOPANTALLAS^Catálogo de Pantallas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.CATALOGOREPORTES^Catálogo de Reportes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.REPORTEPANTALLA^Asignación de Reportes por Pantalla
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.CATALOGOTIPOEXPORTACION^Catálogo de Tipo de Exportación
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.CONFIGURACIONAMSYSEGURIDAD^Configuración para AMS y Seguridad
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.CALENDARIO.REPORTE^Calendarizar ejecución de reportes
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.CONSULTASDINAMICAS^Consultas Dinámicas
(SELECT ID FROM FWK_IDIOMA WHERE COD_IDIOMA='es' AND COD_PAIS='MX')^MENU.CONSULTASDINAMICASCATALOGO^Catálogo de Consultas Dinámicas
